In [1]:
import pandas as pd
import numpy as np
import chainladder as cl

In [ ]:
raa_df = pd.read_csv(
    "https://raw.githubusercontent.com/casact/chainladder-python/master/chainladder/utils/data/raa.csv"
)
raa_df.head(20)

development    0
origin         0
values         0
dtype: int64

- Development: valuation date
- Origin: Accident year

In [4]:
raa_df['maturity'] = (raa_df['development'] - raa_df['origin'])*12 + 12

In [5]:
# We can observe the maturities like so
raa_df.head()

   development  origin  values  maturity
0         1981    1981  5012.0        12
1         1982    1982   106.0        12
2         1983    1983  3410.0        12
3         1984    1984  5655.0        12
4         1985    1985  1092.0        12

In [6]:
# NOTE Chain ladder arguments is not name appropriately
raa = cl.Triangle(
    raa_df,
    origin="origin",
    development="development",
    columns="values",
    cumulative= True
)
raa

         12       24       36       48       60       72       84       96       108      120
1981  5012.0   8269.0  10907.0  11805.0  13539.0  16181.0  18009.0  18608.0  18662.0  18834.0
1982   106.0   4285.0   5396.0  10666.0  13782.0  15599.0  15496.0  16169.0  16704.0      NaN
1983  3410.0   8992.0  13873.0  16141.0  18735.0  22214.0  22863.0  23466.0      NaN      NaN
1984  5655.0  11555.0  15766.0  21266.0  23425.0  26083.0  27067.0      NaN      NaN      NaN
1985  1092.0   9565.0  15836.0  22169.0  25955.0  26180.0      NaN      NaN      NaN      NaN
1986  1513.0   6445.0  11702.0  12935.0  15852.0      NaN      NaN      NaN      NaN      NaN
1987   557.0   4020.0  10946.0  12314.0      NaN      NaN      NaN      NaN      NaN      NaN
1988  1351.0   6947.0  13112.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN
1989  3133.0   5395.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
1990  2063.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

Not too well documented, but I see the point here, it just makes it convenient. A mapping that puts the correct values against the correct ones. I think the printing is using some sort of formatting. 

-  Figure out how the printing works here. Might be useful for showing outputs

In [7]:
raa = cl.load_sample('raa')
raa

         12       24       36       48       60       72       84       96       108      120
1981  5012.0   8269.0  10907.0  11805.0  13539.0  16181.0  18009.0  18608.0  18662.0  18834.0
1982   106.0   4285.0   5396.0  10666.0  13782.0  15599.0  15496.0  16169.0  16704.0      NaN
1983  3410.0   8992.0  13873.0  16141.0  18735.0  22214.0  22863.0  23466.0      NaN      NaN
1984  5655.0  11555.0  15766.0  21266.0  23425.0  26083.0  27067.0      NaN      NaN      NaN
1985  1092.0   9565.0  15836.0  22169.0  25955.0  26180.0      NaN      NaN      NaN      NaN
1986  1513.0   6445.0  11702.0  12935.0  15852.0      NaN      NaN      NaN      NaN      NaN
1987   557.0   4020.0  10946.0  12314.0      NaN      NaN      NaN      NaN      NaN      NaN
1988  1351.0   6947.0  13112.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN
1989  3133.0   5395.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
1990  2063.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

They provided a convenience function too. Might be useful to provide our users with example sets to perform these kinds of calculations.

In [8]:
raa.latest_diagonal

         1990
1981  18834.0
1982  16704.0
1983  23466.0
1984  27067.0
1985  26180.0
1986  15852.0
1987  12314.0
1988  13112.0
1989   5395.0
1990   2063.0

In [8]:
raa.valuation_date

Timestamp('1990-12-31 23:59:59.999999999')

In [9]:
print("Is triangle cumulative?", raa.is_cumulative)
print("Does triangle contain ultimate projections?", raa.is_ultimate)
print("Is this a valuation triangle?", raa.is_val_tri)
print('Has the triangle been "squared"?', raa.is_full)

Is triangle cumulative? True
Does triangle contain ultimate projections? False
Is this a valuation triangle? False
Has the triangle been "squared"? False

In [10]:
print("Origin grain:", raa.origin_grain)
print("Development grain:", raa.development_grain)

Origin grain: Y
Development grain: Y

The above refers to the data granualirity.

In [11]:
clrd_df = pd.read_csv(
    "https://raw.githubusercontent.com/casact/chainladder-python/master/chainladder/utils/data/clrd.csv"
)
clrd_df.head()

,GRCODE,GRNAME,AccidentYear,DevelopmentYear,DevelopmentLag,IncurLoss,CumPaidLoss,BulkLoss,EarnedPremDIR,EarnedPremCeded,EarnedPremNet,Single,PostedReserve97,LOB
0,86,Allstate Ins Co Grp,1988,1988,1,367404,70571,127737,400699,5957,394742,0,281872,wkcomp
1,86,Allstate Ins Co Grp,1988,1989,2,362988,155905,60173,400699,5957,394742,0,281872,wkcomp
2,86,Allstate Ins Co Grp,1988,1990,3,347288,220744,27763,400699,5957,394742,0,281872,wkcomp
3,86,Allstate Ins Co Grp,1988,1991,4,330648,251595,15280,400699,5957,394742,0,281872,wkcomp
4,86,Allstate Ins Co Grp,1988,1992,5,354690,274156,27689,400699,5957,394742,0,281872,wkcomp

In [12]:
clrd = cl.Triangle(
    clrd_df,
    origin="AccidentYear",
    development="DevelopmentYear",
    columns=[
        'IncurLoss',
        'CumPaidLoss',
        'BulkLoss',
        'EarnedPremDIR',
        'EarnedPremCeded',
        'EarnedPremNet',
    ],
    index=['GRNAME', 'LOB'],
    cumulative=True,
)

In [13]:
clrd

                                             Triangle Summary
Valuation:                                            1997-12
Grain:                                                   OYDY
Shape:                                       (775, 6, 10, 10)
Index:                                          [GRNAME, LOB]
Columns:    [IncurLoss, CumPaidLoss, BulkLoss, EarnedPremD...

- Valuation month is Dec 1997
- OYDY -> Origin (Accident) Year, Development Year
- Shape
    - 775: the unique combination of all possible indices
    - 6: Number of triangles (columns mentioned)
    - 10: Number of accident periods
    - 10: Number of valuation periods
- Index: Segmentation level

In [14]:
len((clrd_df['GRNAME'] +clrd_df['LOB']).unique())

775

In [15]:
clrd.index.head()

            GRNAME      LOB
0  Adriatic Ins Co  othliab
1  Adriatic Ins Co   ppauto
2        Aegis Grp  comauto
3        Aegis Grp  othliab
4        Aegis Grp   ppauto

In [16]:
np.sum(clrd.values)

np.float64(nan)

In [17]:
np.nansum(clrd.values)

np.float64(3661713596.0)

In [18]:
clrd[['CumPaidLoss', 'IncurLoss']]

                    Triangle Summary
Valuation:                   1997-12
Grain:                          OYDY
Shape:              (775, 2, 10, 10)
Index:                 [GRNAME, LOB]
Columns:    [CumPaidLoss, IncurLoss]

In [19]:
clrd[clrd["LOB"] == "wkcomp"]

                                             Triangle Summary
Valuation:                                            1997-12
Grain:                                                   OYDY
Shape:                                       (132, 6, 10, 10)
Index:                                          [GRNAME, LOB]
Columns:    [IncurLoss, CumPaidLoss, BulkLoss, EarnedPremD...

In [20]:
clrd.loc['Allstate Ins Co Grp']

                                             Triangle Summary
Valuation:                                            1997-12
Grain:                                                   OYDY
Shape:                                         (2, 6, 10, 10)
Index:                                                  [LOB]
Columns:    [IncurLoss, CumPaidLoss, BulkLoss, EarnedPremD...

In [21]:
clrd.loc['Allstate Ins Co Grp'].index

        LOB
0  prodliab
1    wkcomp

In [22]:
clrd.loc['Allstate Ins Co Grp','wkcomp']

                                             Triangle Summary
Valuation:                                            1997-12
Grain:                                                   OYDY
Shape:                                         (1, 6, 10, 10)
Index:                                          [GRNAME, LOB]
Columns:    [IncurLoss, CumPaidLoss, BulkLoss, EarnedPremD...

In [23]:
clrd.loc['Allstate Ins Co Grp','wkcomp']['CumPaidLoss']

          12        24        36        48        60        72        84        96        108       120
1988  70571.0  155905.0  220744.0  251595.0  274156.0  287676.0  298499.0  304873.0  321808.0  325322.0
1989  66547.0  136447.0  179142.0  211343.0  231430.0  244750.0  254557.0  270059.0  273873.0       NaN
1990  52233.0  133370.0  178444.0  204442.0  222193.0  232940.0  253337.0  256788.0       NaN       NaN
1991  59315.0  128051.0  169793.0  196685.0  213165.0  234676.0  239195.0       NaN       NaN       NaN
1992  39991.0   89873.0  114117.0  133003.0  154362.0  159496.0       NaN       NaN       NaN       NaN
1993  19744.0   47229.0   61909.0   85099.0   87215.0       NaN       NaN       NaN       NaN       NaN
1994  20379.0   46773.0   88636.0   91077.0       NaN       NaN       NaN       NaN       NaN       NaN
1995  18756.0   84712.0   87311.0       NaN       NaN       NaN       NaN       NaN       NaN       NaN
1996  42609.0   44916.0       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN
1997    691.0       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN

In [24]:
clrd['CaseIncurLoss'] = clrd['IncurLoss'] - clrd['BulkLoss']

In [25]:
clrd['PaidToIncurRatio'] = clrd['CumPaidLoss'] / clrd['IncurLoss']

Let's do some neat diagnostics

In [26]:
clrd.loc['Allstate Ins Co Grp','wkcomp']['PaidToIncurRatio']

           12        24        36        48        60        72        84        96        108       120
1988  0.192080  0.429505  0.635622  0.760915  0.772945  0.821715  0.860704  0.873251  0.924319  0.935473
1989  0.197511  0.431135  0.643248  0.697426  0.772732  0.829489  0.850647  0.907786  0.911027       NaN
1990  0.180613  0.428318  0.641931  0.736113  0.803408  0.837712  0.915552  0.913508       NaN       NaN
1991  0.199597  0.461929  0.629471  0.721340  0.785665  0.877038  0.887248       NaN       NaN       NaN
1992  0.219977  0.438236  0.573147  0.708092  0.831410  0.862420       NaN       NaN       NaN       NaN
1993  0.171976  0.411496  0.610181  0.864564  0.899773       NaN       NaN       NaN       NaN       NaN
1994  0.188810  0.434819  0.906948  0.946894       NaN       NaN       NaN       NaN       NaN       NaN
1995  0.186282  0.896841  0.945805       NaN       NaN       NaN       NaN       NaN       NaN       NaN
1996  0.798205  0.877180       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN
1997  0.102751       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN

Loss Ratios here

In [27]:
clrd['CumPaidLoss'].sum() / clrd['EarnedPremNet'].sum()

           12        24        36        48        60        72        84        96        108       120
1988  0.258115  0.509334  0.636753  0.711533  0.755686  0.780206  0.793152  0.800175  0.805963  0.808297
1989  0.268634  0.523039  0.652594  0.728841  0.772701  0.795837  0.808501  0.816591  0.820405       NaN
1990  0.272814  0.524868  0.654580  0.728685  0.767389  0.788847  0.801618  0.807968       NaN       NaN
1991  0.253951  0.489561  0.609332  0.677909  0.715189  0.734607  0.745255       NaN       NaN       NaN
1992  0.259518  0.492747  0.607392  0.671096  0.706613  0.724512       NaN       NaN       NaN       NaN
1993  0.264522  0.495948  0.606111  0.668749  0.702092       NaN       NaN       NaN       NaN       NaN
1994  0.270903  0.494190  0.600480  0.661351       NaN       NaN       NaN       NaN       NaN       NaN
1995  0.265095  0.475502  0.573694       NaN       NaN       NaN       NaN       NaN       NaN       NaN
1996  0.263451  0.458585       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN
1997  0.255201       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN

In [28]:
clrd.groupby("LOB").sum()

                                             Triangle Summary
Valuation:                                            1997-12
Grain:                                                   OYDY
Shape:                                         (6, 8, 10, 10)
Index:                                                  [LOB]
Columns:    [IncurLoss, CumPaidLoss, BulkLoss, EarnedPremD...

In [29]:
np.unique(clrd["LOB"])

array(['comauto', 'medmal', 'othliab', 'ppauto', 'prodliab', 'wkcomp'],
      dtype=object)

### Aggregation Methods

These don't explicitly need to apply to only the index.

In [30]:
clrd.sum(axis="index")

                                             Triangle Summary
Valuation:                                            1997-12
Grain:                                                   OYDY
Shape:                                         (1, 8, 10, 10)
Index:                                          [GRNAME, LOB]
Columns:    [IncurLoss, CumPaidLoss, BulkLoss, EarnedPremD...

Summing with "index" as the axis means that we will get **eight** traingles with 10x10 AY and devlopments. But what do each of those triangles contain?

- "IncurLoss" will contain only summed up terms that come under the Incur loss category.
- The cell in "IncurLoss" that relates to 1990-36 corresponds to AY1990 and Dev of 36 months.
- This cell contains the sum of all values from each index (GRNAME and LOB combination) that corresponds to the Incurred Losses from AY1990 at 36 month maturity.

In [31]:
clrd.sum(axis="index")['IncurLoss']

             12          24          36          48          60          72          84          96          108         120
1988  11644995.0  11674240.0  11653597.0  11630882.0  11593868.0  11551625.0  11463312.0  11420238.0  11415560.0  11396981.0
1989  13123290.0  13118789.0  13113024.0  13050144.0  12959037.0  12866709.0  12787372.0  12757420.0  12743440.0         NaN
1990  14776079.0  14670690.0  14479699.0  14324680.0  14183178.0  14033498.0  13948139.0  13925679.0         NaN         NaN
1991  15318373.0  15112547.0  14877662.0  14615540.0  14380205.0  14205778.0  14154882.0         NaN         NaN         NaN
1992  16828857.0  16457307.0  15999385.0  15538214.0  15249286.0  15161066.0         NaN         NaN         NaN         NaN
1993  18169370.0  17590902.0  17080187.0  16485467.0  16281774.0         NaN         NaN         NaN         NaN         NaN
1994  19414898.0  18609089.0  17854178.0  17521037.0         NaN         NaN         NaN         NaN         NaN         NaN
1995  19502850.0  18668388.0  17901550.0         NaN         NaN         NaN         NaN         NaN         NaN         NaN
1996  19142090.0  17910743.0         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN
1997  18113581.0         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN

In [32]:
clrd.sum(axis="origin").sum(axis="index")["IncurLoss"]

              12           24           36           48          60          72          84          96          108         120
1988  166034383.0  143812695.0  122959282.0  103165964.0  84647348.0  67818676.0  52353705.0  38103337.0  24159000.0  11396981.0

Here we summed up all values from all accident years, though this is theoretically incorrect, as they should have been accounted for the trend differences.

## Accessor Methods

```python
# splits lastname from first name by a comma-delimiter
df['Last_First'].str.split(',')

# pulls the year out of each date in a dataframe column
df['Accident Date'].dt.year 
```

## Dates/Periods

In [33]:
clrd.origin

PeriodIndex(['1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
             '1996', '1997'],
            dtype='period[Y-DEC]', name='origin')

In [34]:
clrd.origin.min()

Period('1988', 'Y-DEC')

dtype=period(Year ending december)

In [35]:
clrd[clrd.origin == clrd.origin.min()].sum()['IncurLoss']
# summed over index

             12          24          36          48          60          72          84          96          108         120
1988  11644995.0  11674240.0  11653597.0  11630882.0  11593868.0  11551625.0  11463312.0  11420238.0  11415560.0  11396981.0

In [36]:
clrd[clrd.valuation > "1990"][clrd.origin <= "1995"].sum()['IncurLoss']

             12          24          36          48          60          72          84          96          108         120
1988         NaN         NaN  11653597.0  11630882.0  11593868.0  11551625.0  11463312.0  11420238.0  11415560.0  11396981.0
1989         NaN  13118789.0  13113024.0  13050144.0  12959037.0  12866709.0  12787372.0  12757420.0  12743440.0         NaN
1990  14776079.0  14670690.0  14479699.0  14324680.0  14183178.0  14033498.0  13948139.0  13925679.0         NaN         NaN
1991  15318373.0  15112547.0  14877662.0  14615540.0  14380205.0  14205778.0  14154882.0         NaN         NaN         NaN
1992  16828857.0  16457307.0  15999385.0  15538214.0  15249286.0  15161066.0         NaN         NaN         NaN         NaN
1993  18169370.0  17590902.0  17080187.0  16485467.0  16281774.0         NaN         NaN         NaN         NaN         NaN
1994  19414898.0  18609089.0  17854178.0  17521037.0         NaN         NaN         NaN         NaN         NaN         NaN
1995  19502850.0  18668388.0  17901550.0         NaN         NaN         NaN         NaN         NaN         NaN         NaN

## Link Ratios

In [37]:
clrd[(clrd.development > 12) & (clrd.development <= 36)].sum()['IncurLoss'].link_ratio

         24-36
1988  0.998232
1989  0.999561
1990  0.986981
1991  0.984458
1992  0.972175
1993  0.970967
1994  0.959433
1995  0.958923
1996       NaN
1997       NaN

In [38]:
clrd.sum()['IncurLoss'].link_ratio

         12-24     24-36     36-48     48-60     60-72     72-84     84-96    96-108   108-120
1988  1.002511  0.998232  0.998051  0.996818  0.996356  0.992355  0.996242  0.999590  0.998372
1989  0.999657  0.999561  0.995205  0.993019  0.992875  0.993834  0.997658  0.998904       NaN
1990  0.992868  0.986981  0.989294  0.990122  0.989447  0.993917  0.998390       NaN       NaN
1991  0.986563  0.984458  0.982382  0.983898  0.987870  0.996417       NaN       NaN       NaN
1992  0.977922  0.972175  0.971176  0.981405  0.994215       NaN       NaN       NaN       NaN
1993  0.968162  0.970967  0.965181  0.987644       NaN       NaN       NaN       NaN       NaN
1994  0.958495  0.959433  0.981341       NaN       NaN       NaN       NaN       NaN       NaN
1995  0.957213  0.958923       NaN       NaN       NaN       NaN       NaN       NaN       NaN
1996  0.935673       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN

In [39]:
clrd[clrd['GRNAME'] == 'Alaska Nat Ins Co']['IncurLoss']

           Triangle Summary
Valuation:          1997-12
Grain:                 OYDY
Shape:       (4, 1, 10, 10)
Index:        [GRNAME, LOB]
Columns:        [IncurLoss]

In [40]:
clrd.loc['Alaska Nat Ins Co','comauto']['EarnedPremNet']

         12      24      36      48      60      72      84      96      108     120
1988  4255.0  4255.0  4255.0  4255.0  4255.0  4255.0  4255.0  4255.0  4255.0  4255.0
1989  4178.0  4178.0  4178.0  4178.0  4178.0  4178.0  4178.0  4178.0  4178.0     NaN
1990  4216.0  4216.0  4216.0  4216.0  4216.0  4216.0  4216.0  4216.0     NaN     NaN
1991  5425.0  5425.0  5425.0  5425.0  5425.0  5425.0  5425.0     NaN     NaN     NaN
1992  5835.0  5835.0  5835.0  5835.0  5835.0  5835.0     NaN     NaN     NaN     NaN
1993  6170.0  6170.0  6170.0  6170.0  6170.0     NaN     NaN     NaN     NaN     NaN
1994  5625.0  5625.0  5625.0  5625.0     NaN     NaN     NaN     NaN     NaN     NaN
1995  5122.0  5122.0  5122.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN
1996  4973.0  4973.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
1997  4308.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN

## Initializing $\triangle$ with own data

In [41]:
# ?cl.Triangle

In [ ]:
prism_df = pd.read_csv(
    "https://raw.githubusercontent.com/casact/chainladder-python/master/chainladder/utils/data/prism.csv"
)
prism_df.head()

,ClaimNo,AccidentDate,ReportDate,Line,Type,ClaimLiability,Limit,Deductible,TotalPayment,PaymentDate,CloseDate,Status,reportedCount,closedPaidCount,closedUnPaidCount,openCount,Paid,Outstanding,Incurred
0,1,2008-01-22,4/19/2010,Home,Dwelling,False,300000.0,20000,0.00000,2010-10-08,10/8/2010,CLOSED,1,0,1,0,0.00000,0,0.00000
1,2,2008-01-02,4/20/2010,Home,Dwelling,False,200000.0,20000,0.00000,2010-11-30,11/30/2010,CLOSED,1,0,1,0,0.00000,0,0.00000
2,3,2008-01-01,9/23/2009,Home,Dwelling,True,200000.0,20000,115744.77370,2010-02-17,2/17/2010,CLOSED,1,1,0,0,115744.77370,0,115744.77370
3,4,2008-01-02,7/25/2009,Home,Dwelling,True,200000.0,20000,63678.87713,2009-11-18,11/18/2009,CLOSED,1,1,0,0,63678.87713,0,63678.87713
4,5,2008-01-16,12/7/2009,Home,Dwelling,True,200000.0,20000,112175.55590,2010-04-30,4/30/2010,CLOSED,1,1,0,0,112175.55590,0,112175.55590

In [43]:
prism_df.dtypes

ClaimNo                int64
AccidentDate          object
ReportDate            object
Line                  object
Type                  object
ClaimLiability          bool
Limit                float64
Deductible             int64
TotalPayment         float64
PaymentDate           object
CloseDate             object
Status                object
reportedCount          int64
closedPaidCount        int64
closedUnPaidCount      int64
openCount              int64
Paid                 float64
Outstanding            int64
Incurred             float64
dtype: object

In [44]:
prism = cl.Triangle(
    data = prism_df,
    origin="AccidentDate",
    development="PaymentDate",
    columns="Paid",
    cumulative=False #(1)
)

1. Data is transactional

In [45]:
prism[(prism.origin <= '2008-05')][prism.development <= 4]

          1             2             3             4
2008-01 NaN           NaN  46915.015123  19898.778972
2008-02 NaN  28749.365091  22109.176517  79032.630204
2008-03 NaN  48805.786934  27949.453343  90412.574923
2008-04 NaN  30758.035988  17762.893769  70872.089511
2008-05 NaN  38672.002824  86973.993208  20482.742048

The given data actually is given in terms of accident years and payment period, and we can use python to view the data in terms of origin and development period. That's really neat as we just need to specify the correct columns. This is phenomenal. Meaning, we are allowed to load the **transactional** data in here directly and do manipulations to it as required. Finally, we can just put it in the `cl.Triangle` and viola! We have the completely ready-to-work triangle.

> NOTE: The minimum supported grain is monthly, but I think that's the point of using a triangle, to benefit from the averaging out higher and lower values within each period.

In [46]:
prism.origin_grain

'M'

In [47]:
prism.development_grain

'M'

In [48]:
prism[prism.origin >= '2017'].link_ratio

               1-2       2-3       3-4       4-5       5-6       6-7       7-8       8-9      9-10     10-11    11-12
2017-01   3.118300  4.662360  0.859077  1.087970  0.759807  1.618957  0.911346  0.520848  1.688666  0.748069  1.93699
2017-02        NaN  2.023418  1.017975  0.916108  0.994596  1.699513  0.884940  0.927946  0.716325  0.631960      NaN
2017-03   4.641206  3.580825  0.971199  1.983722  0.392870  3.736762  0.556320  0.867518  0.916592       NaN      NaN
2017-04        NaN  4.123747  1.221050  1.014541  0.459008  1.422735  0.891478  1.560220       NaN       NaN      NaN
2017-05  12.179742  1.476021  1.480410  1.010912  1.977966  1.123194  0.489569       NaN       NaN       NaN      NaN
2017-06        NaN  1.189978  2.142638  1.497244  0.700424  1.292524       NaN       NaN       NaN       NaN      NaN
2017-07   1.074927  4.073602  0.576930  1.099546  1.490977       NaN       NaN       NaN       NaN       NaN      NaN
2017-08        NaN  7.568035  0.773849  2.132791       NaN       NaN       NaN       NaN       NaN       NaN      NaN
2017-09   1.792261  2.583002  1.767942       NaN       NaN       NaN       NaN       NaN       NaN       NaN      NaN
2017-10        NaN  2.980957       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN      NaN
2017-11   2.592718       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN      NaN

In [49]:
prism = cl.Triangle(
    prism_df,
    origin="AccidentDate",
    development="PaymentDate",
    columns=["Paid", "Incurred"],
    cumulative=False,
)

In [50]:
prism

            Triangle Summary
Valuation:           2017-12
Grain:                  OMDM
Shape:      (1, 2, 120, 120)
Index:               [Total]
Columns:    [Paid, Incurred]

In [51]:
prism_df.head()

,ClaimNo,AccidentDate,ReportDate,Line,Type,ClaimLiability,Limit,Deductible,TotalPayment,PaymentDate,CloseDate,Status,reportedCount,closedPaidCount,closedUnPaidCount,openCount,Paid,Outstanding,Incurred
0,1,2008-01-22,4/19/2010,Home,Dwelling,False,300000.0,20000,0.00000,2010-10-08,10/8/2010,CLOSED,1,0,1,0,0.00000,0,0.00000
1,2,2008-01-02,4/20/2010,Home,Dwelling,False,200000.0,20000,0.00000,2010-11-30,11/30/2010,CLOSED,1,0,1,0,0.00000,0,0.00000
2,3,2008-01-01,9/23/2009,Home,Dwelling,True,200000.0,20000,115744.77370,2010-02-17,2/17/2010,CLOSED,1,1,0,0,115744.77370,0,115744.77370
3,4,2008-01-02,7/25/2009,Home,Dwelling,True,200000.0,20000,63678.87713,2009-11-18,11/18/2009,CLOSED,1,1,0,0,63678.87713,0,63678.87713
4,5,2008-01-16,12/7/2009,Home,Dwelling,True,200000.0,20000,112175.55590,2010-04-30,4/30/2010,CLOSED,1,1,0,0,112175.55590,0,112175.55590

It is good practice to explicitly mention the date format.

In [52]:
prism = cl.Triangle(
    prism_df,
    origin="AccidentDate",
    origin_format="%Y-%m-%d",
    development="PaymentDate",
    development_format="%Y-%m-%d",
    columns=["Paid","Incurred"],
    cumulative=False
)

In [53]:
prism

            Triangle Summary
Valuation:           2017-12
Grain:                  OMDM
Shape:      (1, 2, 120, 120)
Index:               [Total]
Columns:    [Paid, Incurred]

This works for symmetric triangles.

- Symmetric meaning having the same grain for both origin and development periods.

But what about asymmetric triangles?

In [54]:
prism_df['AccYr'] = prism_df['AccidentDate'].str[:4]

prism = cl.Triangle(
    prism_df,
    origin="AccYr",
    origin_format="%Y",
    development="PaymentDate",
    development_format="%Y-%m-%d",
    columns=["Paid","Incurred"],
    cumulative=False
)

In [55]:
prism

            Triangle Summary
Valuation:           2017-12
Grain:                  OYDM
Shape:       (1, 2, 10, 120)
Index:               [Total]
Columns:    [Paid, Incurred]

In [56]:
prism['Paid']

               1             2              3              4              5              6              7              8              9              10             11            12            13            14            15            16            17             18            19             20            21            22             23            24            25            26            27            28            29            30            31            32            33            34            35            36            37            38            39            40            41            42            43            44            45            46            47            48             49             50            51            52            53            54            55            56            57            58            59            60            61            62            63            64            65            66            67            68            69            70            71            72            73            74            75            76           77            78           79           80            81          82      83            84   85   86      87           88           89      90       91          92           93   94   95   96   97   98   99            100  101  102  103  104  105  106  107  108  109  110  111  112  113     114  115  116  117  118  119  120
2008           NaN           NaN   75664.380214   90813.742423  194956.103471  300085.418824  347486.651714  400010.617578  356794.502531  598532.326449  641536.425988  3.983742e+05  7.370244e+05  7.671280e+05  7.341962e+05  5.731743e+05  6.011886e+05  507487.238890  5.262003e+05  454101.038664  4.592687e+05  5.712807e+05  947098.698678  9.086826e+05  3.701474e+05  1.562406e+06  2.415006e+06  2.784466e+06  2.704362e+06  4.546247e+06  4.878159e+06  6.097529e+06  6.037435e+06  1.253314e+07  8.906121e+06  1.058691e+07  7.956213e+06  9.153212e+06  1.077999e+07  1.013129e+07  7.953316e+06  9.281836e+06  5.951154e+06  6.502800e+06  3.651396e+06  2.434386e+06  8.061479e+05  1.128002e+06  317472.619664   26873.221313  75318.053240  54505.399964  40676.115005  10118.603300  11607.561736  23143.087336   7000.000000  42680.332727  30727.022825           NaN  35182.690060  11722.264203  19491.773256   8390.432613           NaN           NaN   1578.971749  29980.600067  34636.956810           NaN   5932.496097  22936.033691           NaN   8351.518321           NaN  21563.293691          NaN  13274.484130  6905.158619  7051.450295           NaN         NaN     NaN  19000.000000  NaN  NaN     NaN          NaN  4751.868062  7000.0  19000.0  5182.60652          NaN  NaN  NaN  NaN  NaN  NaN  NaN  12411.369291  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  7000.0  NaN  NaN  NaN  NaN  NaN  NaN
2009           NaN  24326.814665   80376.045998  136856.648098  175736.898977  297690.337140  358624.070468  325461.635602  529831.969293  540216.723927  556830.668443  5.834332e+05  7.671930e+05  4.859745e+05  7.038561e+05  7.887551e+05  8.759424e+05  714801.340039  5.985041e+05  423752.861179  3.619214e+05  5.596524e+05  634659.052995  4.785295e+05  4.712591e+05  1.647277e+06  1.521688e+06  1.757110e+06  3.142084e+06  4.045939e+06  5.090424e+06  8.524774e+06  8.998482e+06  9.623510e+06  1.323659e+07  1.166428e+07  1.111210e+07  1.004107e+07  1.042377e+07  1.159419e+07  7.894366e+06  6.431454e+06  6.561179e+06  6.370337e+06  2.442785e+06  2.164221e+06  1.056090e+06  1.528802e+05   31965.269691  295714.535436  51422.895883  52724.444105  45404.464826  20357.031655  25607.355442  30396.154054   3462.412866  18329.878692  31737.059878  21549.657455  12265.587530   7254.649009  14735.452863   4555.892746   3911.686172  17247.273140  12347.917460  23092.780648   2222.591893           NaN           NaN           NaN           NaN           NaN           NaN   1656.505479          NaN   2041.114146          NaN          NaN  28594.422270  7000.00000     NaN           NaN  NaN  NaN  7000.0          NaN          NaN     NaN      NaN         NaN          NaN  NaN  NaN  NaN  NaN  NaN  NaN   5349.086903  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN
2010           NaN  22192.478687   84802.181881  148299.169900  200733.035063  208236.728733  456691.819036  519691.226862  604945.654745  484187.788542  632780.962596  7.047602e+05  8.144448e+05  6.401543e+05  8.163333e+05  8.905976e+05  7.457935e+05  586407.574605  6.040598e+05  539012.348748  5.471848e+05  1.055450e+06  501031.917698  5.889855e+05  1.297282e+06  1.232999e+06  2.276618e+06  1.789553e+06  3.719662e+06  4.295247e+06  5.120118e+06  7.224881e+06  5.819877e+06  7.528983e+06  1.020199e+07  1.130605e+07  1.547650e+07  9.001666e+06  1.172561e+07  1.024250e+07  1.061860e+07  7.433986e+06  7.475057e+06  6.116192e+06  3.595327e+06  2.584875e+06  1.979548e+06  5.896805e+05  119130.792114   13248.866623  74152.929302  73547.340893  57667.875344  27694.390061  46271.125512  38644.000529   6774.022366  56907.252677  15184.845737  62644.193703   8365.787771           NaN  35637.752310  16363.714469           NaN  30254.175910           NaN  10027.426360  20663.718512  24368.511522           NaN           NaN  12139.267537  19000.000000           NaN  16734.589225  5786.159693           NaN          NaN          NaN   5918.473408         NaN  7000.0   5852.411423  NaN  NaN     NaN  2695.500913          NaN     NaN      NaN         NaN  7894.971774  NaN  NaN  NaN  NaN  NaN  NaN           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN
2011           NaN  24933.634889   60404.332056  107197.618088  233345.896165  268904.260500  401595.186080  530489.997271  501835.902981  513132.913397  781921.386985  7.014708e+05  8.908045e+05  8.514825e+05  7.776805e+05  1.008484e+06  5.969821e+05  785700.336605  6.557450e+05  696571.952709  6.807257e+05  6.773898e+05  490390.383019  9.459548e+05  1.122673e+06  1.851037e+06  8.995094e+05  1.702261e+06  3.582882e+06  5.331703e+06  5.225728e+06  6.785511e+06  8.506086e+06  1.102146e+07  1.032496e+07  1.170282e+07  1.269239e+07  7.393561e+06  1.143101e+07  1.143921e+07  9.328851e+06  6.473384e+06  6.381945e+06  5.097188e+06  3.492771e+06  3.288215e+06  2.309752e+06  8.448624e+05  335629.098815   50466.914460  60748.707389  29769.789302  51247.018679  22380.244650  23877.106919  72278.522573  63465.796970  26128.125781  35426.082156   3298.677356  10717.789818  41864.867430  29560.679193           NaN  27689.634704  22594.615119   8586.632697  37348.678914  22122.313895   4684.319750   3364.271744  21296.869792   4287.447633  18459.818138  21833.460868           NaN  8618.973329           NaN  2975.908600          NaN           NaN  4214.10132     NaN  12831.808143  NaN  NaN     NaN          NaN          NaN     NaN      NaN         NaN          NaN  NaN  NaN  NaN  NaN  NaN  NaN           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN
2012           NaN  18794.078501   98319.589540  165689.365207  296864.998459  335642.536754  320954.395644  529732.563253  592985.177062  686688.855866  686447.031981  8.519169e+05  1.044212e+06  9.544724e+05  7.541892e+05  7.004901e+05  8.139560e+05  735316.703403  8.434435e+05  610979.771313  7.650731e+05  9.001753e+05  524305.875585  7.705284e+05  7.828616e+05  7.899929e+05  1.103369e+06  2.186602e+06  3.443066e+06  4.221423e+06  7.178965e+06  7.656785e+06  5.590090e+06  8.982027e+06  8.261696e+06  1.359647e+07  1.032970e+07  8.257640e+06  9.321772e+06  8.861009e+06  8.026075e+06  1.151095e+07  5.959513e+06  4.613599e+06  3.586089e+06  2.294259e+06  1.359515e+06  2.037343e+05   15753.578835    4825.817052  35572.887800  47025.437821  43406.274633  79811.940412  63600.307257  46519.756172  21303.389450  11012.139648  58720.963899  42153.387526  30589.656750   6840.626511   7168.640275  37329.362031  21325.172999  42416.968478  14000.000000  30497.072560   8423.825983  12509.598410  13281.714657   7000.000000           NaN           NaN           NaN           NaN          NaN           NaN          NaN          NaN           NaN         NaN     NaN           NaN  NaN  NaN     NaN          NaN          NaN     NaN      NaN         NaN          NaN  NaN  NaN  NaN  NaN  NaN  NaN           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN
2013           NaN  70958.929207   99628.008281  238991.375169  180138.458080  302213.477793  477223.596123  585963.166386  648734.411994  637203.114079  682368.117405  9.662005e+05  7.309051e+05  7.880407e+05  9.338613e+05  8.508193e+05  9.270194e+05  711364.608560  1.126966e+06  742502.695017  5.909403e+05  8.881174e+05  706265.588894  7.213157e+05  9.861389e+05  9.881487e+05  1.225893e+06  2.064617e+06  3.226128e+06  3.337927e+06  7.487120e+06  5.812563e+06  7.699736e+06  1.429176e+07  9.297106e+06  1.339363e+07  1.017609e+07  1.108135e+07  9.348480e+06  8.782365e+06  8.332327e+06  7.631190e+06  5.444235e+06  6.958137e+06  4.240059e+06  2.547624e+06  8.930230e+05  1.256927e+06   65875.866878   49276.243262  76963.405478  95595.756248  66386.070242  44070.197828  81623.175278  13540.121014  16310.835649  25538.965303  22116.041412   5427.390291           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN          NaN           NaN          NaN          NaN           NaN         NaN     NaN           NaN  NaN  NaN     NaN          NaN          NaN     NaN      NaN         NaN          NaN  NaN  NaN  NaN  NaN  NaN  NaN           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN
2014  18193.615004  32771.813803  124801.186194  276336.386415  344634.732900  425874.521138  449242.485198  541203.495636  587788.640766  819083.073241  841927.820373  1.084300e+06  8.273738e+05  7.725394e+05  1.198817e+06  1.035734e+06  9.333597e+05  900446.997494  9.926431e+05  845639.783362  6.242145e+05  9.333139e+05  801369.552914  9.965165e+05  1.241265e+06  1.041576e+06  1.543091e+06  2.354836e+06  3.608809e+06  3.150000e+06  4.227372e+06  7.183240e+06  7.418863e+06  7.616530e+06  1.101130e+07  1.045179e+07  9.890481e+06  1.290310e+07  8.542991e+06  8.713766e+06  9.246068e+06  6.866563e+06  7.833314e+06  3.985606e+06  4.056370e+06  3.694519e+06  1.095143e+06  8.852198e+05            NaN            NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN          NaN           NaN          NaN          NaN           NaN         NaN     NaN           NaN  NaN  NaN     NaN          NaN          NaN     NaN      NaN         NaN          NaN  NaN  NaN  NaN  NaN  NaN  NaN           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN
2015           NaN  31221.487507   86418.061760  242766.433412  276598.476769  418870.290158  575633.983430  620097.757031  858771.326075  787202.598401  973846.616159  1.037602e+06  1.152322e+06  9.494363e+05  1.132752e+06  8.509203e+05  1.040219e+06  969420.903319  1.018208e+06  942013.142755  8.851064e+05  1.003449e+06  778933.792936  7.958000e+05  1.122678e+06  8.086954e+05  2.222553e+06  3.433307e+06  3.693775e+06  4.020768e+06  3.646026e+06  8.476120e+06  7.538322e+06  8.573633e+06  1.070603e+07  9.245065e+06           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN            NaN            NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN          NaN           NaN          NaN          NaN           NaN         NaN     NaN           NaN  NaN  NaN     NaN          NaN          NaN     NaN      NaN         NaN          NaN  NaN  NaN  NaN  NaN  NaN  NaN           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN
2016   3213.543940  30412.313959   87680.467853  238883.577926  325065.112525  468785.338384  521980.504768  560611.271358  853548.382899  976906.136902  910871.647045  1.103004e+06  1.348982e+06  1.056142e+06  1.186347e+06  1.164726e+06  1.141416e+06  922542.939622  9.558699e+05  827461.089202  1.057683e+06  1.072619e+06  636696.163982  1.136609e+06           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN            NaN            NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN          NaN           NaN          NaN          NaN           NaN         NaN     NaN           NaN  NaN  NaN     NaN          NaN          NaN     NaN      NaN         NaN          NaN  NaN  NaN  NaN  NaN  NaN  NaN           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN
2017   8337.875863  26000.000000  175935.102301  226565.055999  324943.428611  416752.154857  646836.256429  649984.979125  811832.021102  957490.473881  923912.780655  1.227946e+06           NaN           NaN           NaN           NaN           NaN            NaN           NaN            NaN           NaN           NaN            NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN            NaN            NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN          NaN           NaN          NaN          NaN           NaN         NaN     NaN           NaN  NaN  NaN     NaN          NaN          NaN     NaN      NaN         NaN          NaN  NaN  NaN  NaN  NaN  NaN  NaN           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN

For a 1D triangle, simply omit the `development` argument

In [ ]:
prism_df["Premium"] = 3 * prism_df["Incurred"]

prism = cl.Triangle(
    prism_df,
    origin="AccidentDate",
    origin_format="%Y-%m-%d",
    columns="Premium",
    cumulative=False
)
prism.head()

              2017-12
2008-01  4.187229e+07
2008-02  4.354268e+07
2008-03  3.592080e+07
2008-04  3.052159e+07
2008-05  4.680761e+07
2008-06  3.592624e+07
2008-07  3.330561e+07
2008-08  3.566795e+07
2008-09  3.677317e+07
2008-10  3.685877e+07
2008-11  4.193904e+07
2008-12  3.471688e+07
2009-01  4.043509e+07
2009-02  5.180367e+07
2009-03  3.827396e+07
2009-04  4.404504e+07
2009-05  3.857352e+07
2009-06  3.467500e+07
2009-07  3.937263e+07
2009-08  4.193669e+07
2009-09  3.912008e+07
2009-10  3.348542e+07
2009-11  3.588476e+07
2009-12  3.564036e+07
2010-01  3.918751e+07
2010-02  3.640811e+07
2010-03  4.610033e+07
2010-04  3.931191e+07
2010-05  3.861744e+07
2010-06  3.820465e+07
2010-07  3.901837e+07
2010-08  4.156632e+07
2010-09  3.908993e+07
2010-10  4.236063e+07
2010-11  4.164149e+07
2010-12  4.410378e+07
2011-01  4.455028e+07
2011-02  4.022343e+07
2011-03  4.083951e+07
2011-04  4.290512e+07
2011-05  3.799259e+07
2011-06  4.000331e+07
2011-07  4.249876e+07
2011-08  3.861800e+07
2011-09  4.187191e+07
2011-10  4.184378e+07
2011-11  3.917826e+07
2011-12  3.694711e+07
2012-01  3.788083e+07
2012-02  4.270029e+07
2012-03  4.653762e+07
2012-04  3.785465e+07
2012-05  3.693307e+07
2012-06  3.914957e+07
2012-07  3.893848e+07
2012-08  3.586909e+07
2012-09  3.110809e+07
2012-10  4.205510e+07
2012-11  3.560778e+07
2012-12  3.382385e+07
2013-01  4.813855e+07
2013-02  3.458431e+07
2013-03  4.096955e+07
2013-04  3.508083e+07
2013-05  4.537744e+07
2013-06  4.477441e+07
2013-07  4.143155e+07
2013-08  4.576263e+07
2013-09  4.198754e+07
2013-10  4.120169e+07
2013-11  3.225811e+07
2013-12  3.345250e+07
2014-01  4.036345e+07
2014-02  3.864147e+07
2014-03  3.639684e+07
2014-04  3.578460e+07
2014-05  3.745228e+07
2014-06  4.515285e+07
2014-07  3.963638e+07
2014-08  3.671515e+07
2014-09  4.552311e+07
2014-10  3.117016e+07
2014-11  4.338274e+07
2014-12  3.469077e+07
2015-01  3.697209e+07
2015-02  3.418734e+07
2015-03  3.540646e+07
2015-04  3.213757e+07
2015-05  2.365461e+07
2015-06  1.670796e+07
2015-07  1.807573e+07
2015-08  1.220446e+07
2015-09  1.120974e+07
2015-10  7.647748e+06
2015-11  6.591418e+06
2015-12  7.948603e+06
2016-01  5.502819e+06
2016-02  5.677216e+06
2016-03  4.541502e+06
2016-04  4.938965e+06
2016-05  4.522476e+06
2016-06  4.664779e+06
2016-07  5.134766e+06
2016-08  4.554252e+06
2016-09  4.406520e+06
2016-10  4.278755e+06
2016-11  3.955199e+06
2016-12  3.586924e+06
2017-01  3.446326e+06
2017-02  3.095700e+06
2017-03  2.680826e+06
2017-04  2.634972e+06
2017-05  2.057550e+06
2017-06  1.403713e+06
2017-07  1.375008e+06
2017-08  1.130442e+06
2017-09  8.703196e+05
2017-10  4.184447e+05
2017-11  4.406235e+04
2017-12  3.224408e+04

Let's segment our data now

In [58]:
prism = cl.Triangle(
    prism_df,
    origin='AccidentDate',
    origin_format="%Y-%m-%d",
    development="PaymentDate",
    development_format="%Y-%m-%d",
    columns=["Paid","Incurred"],
    index=['Line','Type'],
    cumulative=False
)
prism

            Triangle Summary
Valuation:           2017-12
Grain:                  OMDM
Shape:      (2, 2, 120, 120)
Index:          [Line, Type]
Columns:    [Paid, Incurred]

In [68]:
prism.index

   Line      Type
0  Auto        PD
1  Home  Dwelling

In [74]:
prism[prism['Line']=='Auto']['Paid']

                  1             2              3              4              5              6              7              8              9              10             11             12             13             14             15             16             17             18            19             20            21            22            23            24            25            26            27            28            29            30            31            32            33            34            35            36            37            38            39            40            41            42            43            44            45            46            47            48            49            50            51            52            53            54            55            56            57            58            59            60            61            62            63            64           65            66            67           68            69   70            71            72          73           74       75            76           77   78           79           80   81          82          83      84   85      86            87   88   89           90           91   92   93           94   95   96   97           98   99   100  101  102  103  104  105     106  107  108  109  110  111  112  113  114  115  116  117  118  119  120
2008-01           NaN           NaN   46915.015123   19898.778972   57215.983936   89783.258084   18301.827646   95054.432894   10332.363153   91772.229823   50403.256100   25904.392469   20363.039991   53973.827076   42845.725397   72887.347019   45247.565785   41837.701048  19000.000000   20681.849010   7437.519458  66622.733500  33915.205090  21437.716875  31795.146380  44186.089101           NaN  14000.000000   7957.721182  21209.812722   7012.978827           NaN   3993.634628  35860.138055  12302.317120           NaN           NaN   5689.926240   7000.000000           NaN   8733.822202           NaN   7324.582575           NaN           NaN           NaN           NaN           NaN           NaN   6908.747829           NaN           NaN           NaN           NaN           NaN           NaN           NaN   5659.301494           NaN           NaN   7509.548931           NaN           NaN           NaN          NaN           NaN           NaN          NaN           NaN  NaN           NaN           NaN         NaN          NaN      NaN           NaN          NaN  NaN          NaN          NaN  NaN         NaN         NaN     NaN  NaN     NaN           NaN  NaN  NaN          NaN          NaN  NaN  NaN          NaN  NaN  NaN  NaN          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2008-02           NaN  28749.365091   22109.176517   79032.630204   63454.689224   59993.109001   64682.696457   68501.669363   33694.528307   71670.163132   10845.932008   76992.306674   45118.695949   31260.402970   31628.854136   44746.068059    5437.649534   28559.099760  20605.070884   23776.507583  36015.909581  40592.274834   4023.598412  23716.146264  16167.228653  34428.684560  15789.407142  11296.884727  13567.485712   3869.908718  10185.902693           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN  14000.000000           NaN           NaN           NaN   7000.000000           NaN  13471.002738   9292.483535           NaN   2696.680976           NaN           NaN           NaN   4607.561736  19000.000000           NaN  29395.358080           NaN           NaN           NaN           NaN           NaN           NaN           NaN          NaN           NaN           NaN  5688.953874           NaN  NaN   6803.309901           NaN         NaN          NaN      NaN           NaN          NaN  NaN          NaN          NaN  NaN         NaN         NaN     NaN  NaN     NaN           NaN  NaN  NaN          NaN          NaN  NaN  NaN          NaN  NaN  NaN  NaN          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2008-03           NaN  48805.786934   27949.453343   90412.574923   54556.680461   83507.369630   12591.483469   72035.009198   70352.890543   35222.888014   52924.695857   51321.624646   72800.675832   49987.284069   55533.845242   51487.533043   62122.202241   60517.179547  87292.816315     568.051158  29542.083952  34545.104829  27905.427801  38143.270557  47144.633122   4534.961367  34888.730946   6688.350540           NaN   5166.536417   6362.890137           NaN  16912.316907   6217.621657   2757.962710           NaN  33000.000000   1881.612725           NaN           NaN   1000.853922   8969.105379  24471.371758           NaN  11748.314370           NaN           NaN           NaN           NaN  26000.000000           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN          NaN   6619.249157           NaN          NaN           NaN  NaN           NaN           NaN         NaN          NaN      NaN           NaN          NaN  NaN          NaN          NaN  NaN         NaN         NaN     NaN  NaN     NaN           NaN  NaN  NaN          NaN          NaN  NaN  NaN          NaN  NaN  NaN  NaN  2005.192531  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2008-04           NaN  30758.035988   17762.893769   70872.089511   30232.607725   39494.326674   66729.041632  122100.008971   20997.801217   38218.309668   25099.184168   57116.190737   15314.140055   40254.315090   19133.327261   26000.000000   18733.664985   53368.886734  21912.843431   10306.440238  34501.288888  29537.719020  14847.002433   6280.113123  15270.018792           NaN  14978.174869           NaN   7000.000000  12221.088414   9351.631356  11775.332160  41234.972552           NaN   7345.131306           NaN   2487.046101  16939.659046   7050.342612           NaN           NaN  15151.604090           NaN           NaN           NaN  14180.136129   5380.837759           NaN   7000.000000   4562.797748           NaN           NaN   3112.936227           NaN           NaN           NaN           NaN           NaN   2965.995285           NaN           NaN           NaN           NaN           NaN          NaN           NaN           NaN          NaN           NaN  NaN           NaN           NaN         NaN          NaN      NaN   6905.158619          NaN  NaN          NaN          NaN  NaN         NaN         NaN     NaN  NaN     NaN           NaN  NaN  NaN          NaN          NaN  NaN  NaN          NaN  NaN  NaN  NaN          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2008-05           NaN  38672.002824   86973.993208   20482.742048   58399.893977  112014.627961   31353.769533   22456.706601   53777.576031   93303.380912   67147.804506   56185.463227   57445.177874   47567.761935   42031.695290   50712.485157   92748.951997   37002.772745  54789.026507   15321.048402  56936.887566   3998.701612   9215.389182  13690.605412  15650.247601   6510.310273   2793.854286   7880.917625           NaN   4548.714568   7000.000000  19000.000000   5544.513489   6945.202544           NaN   4994.194102           NaN  21628.417071  24197.416537           NaN   5988.910750   4224.881747   7000.000000   1167.332199           NaN   4868.954823           NaN           NaN           NaN           NaN           NaN           NaN           NaN   3970.064758           NaN           NaN   2521.327635           NaN           NaN           NaN           NaN           NaN           NaN           NaN          NaN           NaN           NaN          NaN           NaN  NaN           NaN           NaN         NaN          NaN      NaN   7051.450295          NaN  NaN          NaN          NaN  NaN         NaN         NaN     NaN  NaN     NaN  19000.000000  NaN  NaN          NaN          NaN  NaN  NaN          NaN  NaN  NaN  NaN          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2008-06           NaN  56788.951887   73350.983156   97840.012755   64816.230160   61083.172325   41685.246943   87171.779554   61417.669199   63097.186796   20006.680765   47075.459591   52287.664795   14270.298675   22736.166918   16373.506089   40118.505861   23743.675639  87540.885935   16206.638929  17191.198254   7739.420104  28190.498178  24880.985746   9783.481826   7000.000000  23299.381076   4642.496925   7000.000000  44684.401385  17251.404095  10191.601490  10834.401915   1593.055207   2471.571406           NaN           NaN           NaN           NaN   5151.648820           NaN  11330.047576           NaN           NaN           NaN  15855.145410   5406.788588           NaN           NaN   7000.000000           NaN           NaN           NaN           NaN           NaN           NaN           NaN  12078.357180           NaN           NaN           NaN           NaN           NaN           NaN          NaN           NaN           NaN          NaN           NaN  NaN   4755.551245           NaN         NaN          NaN      NaN           NaN          NaN  NaN          NaN          NaN  NaN         NaN         NaN     NaN  NaN     NaN           NaN  NaN  NaN          NaN          NaN  NaN  NaN          NaN  NaN  NaN  NaN          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2008-07           NaN  27867.438010   45803.748629   61495.415066   73279.254948   71590.758310  111807.121771   80249.149104   40631.887383   32433.954204   51969.431012   34789.100369   53686.757541   42535.242123   40374.942262   14232.975097   19539.866708   22674.709098   8906.188985   30519.478914  20927.523404   6712.888032  28262.207381  20612.145945  14000.000000  25910.450716   6533.044835   6213.085071           NaN  31165.806494           NaN  21828.389363  19951.879010  10753.745080   1192.266528   4021.765754   9606.139028   7000.000000   3502.156729           NaN           NaN  10745.962575           NaN           NaN  29601.305897  10635.267238   2254.875111  10118.603300           NaN   1030.151109           NaN           NaN   7571.562484           NaN   5988.307359           NaN           NaN           NaN           NaN           NaN   1578.971749           NaN           NaN           NaN          NaN           NaN           NaN          NaN           NaN  NaN           NaN  13274.484130         NaN          NaN      NaN           NaN          NaN  NaN          NaN          NaN  NaN         NaN         NaN  7000.0  NaN     NaN           NaN  NaN  NaN          NaN          NaN  NaN  NaN          NaN  NaN  NaN  NaN          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2008-08   4832.347658  23831.004511   52510.972980   62649.428820   45955.021136  133133.176956   81732.676394   39709.453582  112115.389608   21367.124066   19386.667046   36759.360580   31528.994879   41324.515512   10346.951390   24925.025056    5431.341940   30605.798472  35527.671788   21604.104855  14842.511530  50919.817947  48521.370007   9975.491207  36263.876300           NaN  25771.828090           NaN  11591.065936   6853.646559           NaN           NaN           NaN   4428.554878           NaN           NaN           NaN           NaN           NaN  11623.029590           NaN           NaN           NaN  14000.000000           NaN  17870.504328           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN   7413.416076           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN          NaN           NaN           NaN          NaN           NaN  NaN           NaN           NaN         NaN          NaN      NaN           NaN          NaN  NaN          NaN          NaN  NaN         NaN         NaN     NaN  NaN     NaN           NaN  NaN  NaN          NaN          NaN  NaN  NaN          NaN  NaN  NaN  NaN          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2008-09           NaN  43464.271322   86156.783771   52664.111596   89928.135042   88738.316556   55617.430853   26599.214109   69521.599239   46788.360093  118862.882889   41956.949936   37001.390416   23008.928446   44061.076102   69775.279709   16980.732775   51150.535770  32458.566343            NaN  11811.942998  26888.471654  11780.700614  15646.102028  21583.716615  48999.799661  14225.892746  11958.138796   7687.325010  14306.024320           NaN           NaN           NaN  14554.180459  18476.774508           NaN   5185.984593   2156.249390   4760.959323           NaN           NaN   9714.680902           NaN   5463.344138           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN  12781.630410   3819.546270           NaN   2569.502182           NaN           NaN           NaN  14000.000000           NaN           NaN           NaN           NaN          NaN           NaN           NaN          NaN           NaN  NaN           NaN           NaN         NaN          NaN      NaN           NaN          NaN  NaN          NaN          NaN  NaN         NaN         NaN     NaN  NaN     NaN           NaN  NaN  NaN          NaN          NaN  NaN  NaN          NaN  NaN  NaN  NaN          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  7000.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2008-10           NaN  12487.697845   21939.093970   53387.901664   52414.633499   92085.830208   45780.592380   72242.152596   83359.423616   47594.115342   48843.809489    9119.705633   38617.176529   65675.754037   93119.937833   13257.633515   66116.511243   53554.223334  44766.285466   34460.085413   7000.000000  26839.191902  23450.012771   3927.984779           NaN  24460.059870  23538.543720           NaN  11755.994889   3102.832917  24540.108190  26934.432200  22320.065460   7000.000000  17313.638340  10413.258080           NaN   5885.523716           NaN           NaN           NaN   5082.916416           NaN           NaN           NaN           NaN           NaN           NaN           NaN   7375.380640           NaN           NaN   4936.722648           NaN           NaN           NaN           NaN           NaN           NaN   9948.002936           NaN           NaN           NaN           NaN          NaN           NaN           NaN          NaN           NaN  NaN           NaN           NaN         NaN          NaN  19000.0           NaN          NaN  NaN          NaN          NaN  NaN         NaN  5182.60652     NaN  NaN     NaN           NaN  NaN  NaN          NaN  10406.17676  NaN  NaN          NaN  NaN  NaN  NaN          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2008-11           NaN  45472.755295    9415.617959   78967.025155   84826.273711   39548.905384   41010.734986   73999.698639   33256.841532   35802.072139   18807.273945   30132.184154   40017.913484   58925.091208   81300.124564   22216.288423   36111.692877   46413.421083  50966.207115   22597.547987  16528.096449  14272.128099  13331.856220  55333.236238  54907.641971  21912.972789   8172.736410  13092.455750  14000.000000  14638.923074   2606.457345           NaN   4852.580999   4484.381644  18312.987192  10608.848790  20258.422688   6727.819353  14000.000000           NaN   8082.004541           NaN           NaN           NaN           NaN           NaN   7000.000000           NaN   3712.052711           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN   5932.496097  16132.723790           NaN           NaN          NaN   1105.273466           NaN          NaN           NaN  NaN           NaN           NaN         NaN          NaN      NaN           NaN          NaN  NaN  4751.868062          NaN  NaN         NaN         NaN     NaN  NaN     NaN           NaN  NaN  NaN          NaN          NaN  NaN  NaN          NaN  NaN  NaN  NaN          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2008-12   3639.502909   9904.705552   54791.839666   87057.302648   70686.463486   54775.095737   31412.351511   44057.009039   59447.553597   31642.731145   44981.974318   49241.534981   50550.067015   32998.974483   38815.052817   14061.835456   42444.998823   52539.777324  24604.214211   30103.121287  38331.855839  22619.850473  31851.110429   6282.865132  32675.477506  14689.466165  13433.116463  26756.943247   7000.000000   7000.000000  21536.897908   8354.139105  14586.069790           NaN   9761.216244           NaN           NaN           NaN           NaN           NaN           NaN  15987.937818           NaN           NaN           NaN           NaN   3655.608395  12068.026990           NaN   6381.875725           NaN           NaN   5820.930431           NaN           NaN           NaN   9361.350910  19000.000000           NaN           NaN           NaN           NaN   8351.518321           NaN  15702.46898           NaN           NaN          NaN           NaN  NaN           NaN           NaN         NaN          NaN      NaN           NaN          NaN  NaN          NaN          NaN  NaN         NaN         NaN     NaN  NaN     NaN           NaN  NaN  NaN          NaN          NaN  NaN  NaN          NaN  NaN  NaN  NaN          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2009-01           NaN  14021.486015   45349.958770   51207.625889   35519.703109   81654.827332   54274.757805   41537.842915   74129.345419   47961.811624   55931.794611   65393.355089   63990.393783   54510.390802   62821.018364   47640.001894            NaN   30595.407200  38253.062912   12150.695023  31359.932877  12381.498748  36191.084471  42117.710111   5203.586900  35735.419436  26471.839696  21980.669709   5361.300013  10206.344290   9389.984756  12923.467357           NaN  22651.865147  21308.142815           NaN   7000.000000           NaN   7000.000000  19059.154550   7000.000000  14000.000000           NaN   2398.895599  11721.175020           NaN           NaN   6398.230585           NaN           NaN           NaN           NaN           NaN           NaN           NaN   7806.579460   3462.412866           NaN           NaN           NaN           NaN           NaN           NaN           NaN          NaN           NaN           NaN  6443.641925           NaN  NaN           NaN           NaN         NaN          NaN      NaN           NaN          NaN  NaN          NaN          NaN  NaN         NaN         NaN     NaN  NaN     NaN           NaN  NaN  NaN          NaN          NaN  NaN  NaN          NaN  NaN  NaN  NaN          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [75]:
prism_cum = prism.incr_to_cum()
prism_cum[prism_cum['Line']=='Auto']['Paid']

                  1              2              3              4              5              6              7              8              9             10            11            12            13            14            15            16            17            18            19            20            21            22            23            24            25            26            27            28            29            30            31            32            33            34            35            36            37            38            39            40            41            42            43            44            45            46            47            48            49            50            51            52            53            54            55            56            57            58            59            60            61            62            63            64            65            66            67            68            69            70            71            72            73            74            75            76            77            78            79            80            81            82            83            84            85            86            87            88            89            90            91            92            93            94            95            96            97            98            99            100           101           102           103           104           105           106           107           108           109           110           111           112           113           114           115           116           117           118           119           120
2008-01           NaN            NaN   46915.015123   66813.794095  124029.778031  213813.036115  232114.863761  327169.296655  337501.659808  4.292739e+05  4.796771e+05  5.055815e+05  5.259446e+05  5.799184e+05  6.227641e+05  6.956515e+05  7.408990e+05  7.827367e+05  8.017367e+05  8.224186e+05  8.298561e+05  8.964788e+05  9.303941e+05  9.518318e+05  9.836269e+05  1.027813e+06  1.027813e+06  1.041813e+06  1.049771e+06  1.070981e+06  1.077994e+06  1.077994e+06  1.081987e+06  1.117847e+06  1.130150e+06  1.130150e+06  1.130150e+06  1.135840e+06  1.142840e+06  1.142840e+06  1.151573e+06  1.151573e+06  1.158898e+06  1.158898e+06  1.158898e+06  1.158898e+06  1.158898e+06  1.158898e+06  1.158898e+06  1.165807e+06  1.165807e+06  1.165807e+06  1.165807e+06  1.165807e+06  1.165807e+06  1.165807e+06  1.165807e+06  1.171466e+06  1.171466e+06  1.171466e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06  1.178976e+06
2008-02           NaN   28749.365091   50858.541608  129891.171812  193345.861036  253338.970037  318021.666494  386523.335857  420217.864164  4.918880e+05  5.027340e+05  5.797263e+05  6.248450e+05  6.561054e+05  6.877342e+05  7.324803e+05  7.379179e+05  7.664770e+05  7.870821e+05  8.108586e+05  8.468745e+05  8.874668e+05  8.914904e+05  9.152065e+05  9.313738e+05  9.658025e+05  9.815919e+05  9.928887e+05  1.006456e+06  1.010326e+06  1.020512e+06  1.020512e+06  1.020512e+06  1.020512e+06  1.020512e+06  1.020512e+06  1.020512e+06  1.020512e+06  1.020512e+06  1.020512e+06  1.034512e+06  1.034512e+06  1.034512e+06  1.034512e+06  1.041512e+06  1.041512e+06  1.054983e+06  1.064276e+06  1.064276e+06  1.066972e+06  1.066972e+06  1.066972e+06  1.066972e+06  1.071580e+06  1.090580e+06  1.090580e+06  1.119975e+06  1.119975e+06  1.119975e+06  1.119975e+06  1.119975e+06  1.119975e+06  1.119975e+06  1.119975e+06  1.119975e+06  1.119975e+06  1.119975e+06  1.125664e+06  1.125664e+06  1.125664e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06  1.132467e+06           NaN
2008-03           NaN   48805.786934   76755.240277  167167.815200  221724.495661  305231.865291  317823.348760  389858.357958  460211.248501  4.954341e+05  5.483588e+05  5.996805e+05  6.724811e+05  7.224684e+05  7.780023e+05  8.294898e+05  8.916120e+05  9.521292e+05  1.039422e+06  1.039990e+06  1.069532e+06  1.104077e+06  1.131983e+06  1.170126e+06  1.217271e+06  1.221806e+06  1.256694e+06  1.263383e+06  1.263383e+06  1.268549e+06  1.274912e+06  1.274912e+06  1.291824e+06  1.298042e+06  1.300800e+06  1.300800e+06  1.333800e+06  1.335682e+06  1.335682e+06  1.335682e+06  1.336682e+06  1.345652e+06  1.370123e+06  1.370123e+06  1.381871e+06  1.381871e+06  1.381871e+06  1.381871e+06  1.381871e+06  1.407871e+06  1.407871e+06  1.407871e+06  1.407871e+06  1.407871e+06  1.407871e+06  1.407871e+06  1.407871e+06  1.407871e+06  1.407871e+06  1.407871e+06  1.407871e+06  1.407871e+06  1.407871e+06  1.407871e+06  1.407871e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.414490e+06  1.416496e+06  1.416496e+06  1.416496e+06  1.416496e+06  1.416496e+06  1.416496e+06  1.416496e+06  1.416496e+06  1.416496e+06  1.416496e+06  1.416496e+06  1.416496e+06  1.416496e+06  1.416496e+06  1.416496e+06  1.416496e+06  1.416496e+06  1.416496e+06  1.416496e+06  1.416496e+06  1.416496e+06           NaN           NaN
2008-04           NaN   30758.035988   48520.929757  119393.019268  149625.626993  189119.953667  255848.995299  377949.004270  398946.805487  4.371651e+05  4.622643e+05  5.193805e+05  5.346946e+05  5.749489e+05  5.940823e+05  6.200823e+05  6.388159e+05  6.921848e+05  7.140977e+05  7.244041e+05  7.589054e+05  7.884431e+05  8.032901e+05  8.095702e+05  8.248403e+05  8.248403e+05  8.398184e+05  8.398184e+05  8.468184e+05  8.590395e+05  8.683911e+05  8.801665e+05  9.214014e+05  9.214014e+05  9.287466e+05  9.287466e+05  9.312336e+05  9.481733e+05  9.552236e+05  9.552236e+05  9.552236e+05  9.703752e+05  9.703752e+05  9.703752e+05  9.703752e+05  9.845554e+05  9.899362e+05  9.899362e+05  9.969362e+05  1.001499e+06  1.001499e+06  1.001499e+06  1.004612e+06  1.004612e+06  1.004612e+06  1.004612e+06  1.004612e+06  1.004612e+06  1.007578e+06  1.007578e+06  1.007578e+06  1.007578e+06  1.007578e+06  1.007578e+06  1.007578e+06  1.007578e+06  1.007578e+06  1.007578e+06  1.007578e+06  1.007578e+06  1.007578e+06  1.007578e+06  1.007578e+06  1.007578e+06  1.007578e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06  1.014483e+06           NaN           NaN           NaN
2008-05           NaN   38672.002824  125645.996032  146128.738080  204528.632057  316543.260018  347897.029551  370353.736152  424131.312183  5.174347e+05  5.845825e+05  6.407680e+05  6.982131e+05  7.457809e+05  7.878126e+05  8.385251e+05  9.312740e+05  9.682768e+05  1.023066e+06  1.038387e+06  1.095324e+06  1.099322e+06  1.108538e+06  1.122228e+06  1.137879e+06  1.144389e+06  1.147183e+06  1.155064e+06  1.155064e+06  1.159613e+06  1.166613e+06  1.185613e+06  1.191157e+06  1.198102e+06  1.198102e+06  1.203096e+06  1.203096e+06  1.224725e+06  1.248922e+06  1.248922e+06  1.254911e+06  1.259136e+06  1.266136e+06  1.267303e+06  1.267303e+06  1.272172e+06  1.272172e+06  1.272172e+06  1.272172e+06  1.272172e+06  1.272172e+06  1.272172e+06  1.272172e+06  1.276142e+06  1.276142e+06  1.276142e+06  1.278664e+06  1.278664e+06  1.278664e+06  1.278664e+06  1.278664e+06  1.278664e+06  1.278664e+06  1.278664e+06  1.278664e+06  1.278664e+06  1.278664e+06  1.278664e+06  1.278664e+06  1.278664e+06  1.278664e+06  1.278664e+06  1.278664e+06  1.278664e+06  1.278664e+06  1.285715e+06  1.285715e+06  1.285715e+06  1.285715e+06  1.285715e+06  1.285715e+06  1.285715e+06  1.285715e+06  1.285715e+06  1.285715e+06  1.285715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06  1.304715e+06           NaN           NaN           NaN           NaN
2008-06           NaN   56788.951887  130139.935043  227979.947798  292796.177958  353879.350283  395564.597226  482736.376780  544154.045979  6.072512e+05  6.272579e+05  6.743334e+05  7.266210e+05  7.408913e+05  7.636275e+05  7.800010e+05  8.201195e+05  8.438632e+05  9.314041e+05  9.476107e+05  9.648019e+05  9.725413e+05  1.000732e+06  1.025613e+06  1.035396e+06  1.042396e+06  1.065696e+06  1.070338e+06  1.077338e+06  1.122023e+06  1.139274e+06  1.149466e+06  1.160300e+06  1.161893e+06  1.164365e+06  1.164365e+06  1.164365e+06  1.164365e+06  1.164365e+06  1.169516e+06  1.169516e+06  1.180846e+06  1.180846e+06  1.180846e+06  1.180846e+06  1.196701e+06  1.202108e+06  1.202108e+06  1.202108e+06  1.209108e+06  1.209108e+06  1.209108e+06  1.209108e+06  1.209108e+06  1.209108e+06  1.209108e+06  1.209108e+06  1.221187e+06  1.221187e+06  1.221187e+06  1.221187e+06  1.221187e+06  1.221187e+06  1.221187e+06  1.221187e+06  1.221187e+06  1.221187e+06  1.221187e+06  1.221187e+06  1.221187e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06  1.225942e+06           NaN           NaN           NaN           NaN           NaN
2008-07           NaN   27867.438010   73671.186639  135166.601705  208445.856653  280036.614963  391843.736734  472092.885838  512724.773221  5.451587e+05  5.971282e+05  6.319173e+05  6.856040e+05  7.281393e+05  7.685142e+05  7.827472e+05  8.022870e+05  8.249618e+05  8.338679e+05  8.643874e+05  8.853149e+05  8.920278e+05  9.202900e+05  9.409022e+05  9.549022e+05  9.808126e+05  9.873457e+05  9.935588e+05  9.935588e+05  1.024725e+06  1.024725e+06  1.046553e+06  1.066505e+06  1.077259e+06  1.078451e+06  1.082473e+06  1.092079e+06  1.099079e+06  1.102581e+06  1.102581e+06  1.102581e+06  1.113327e+06  1.113327e+06  1.113327e+06  1.142928e+06  1.153563e+06  1.155818e+06  1.165937e+06  1.165937e+06  1.166967e+06  1.166967e+06  1.166967e+06  1.174539e+06  1.174539e+06  1.180527e+06  1.180527e+06  1.180527e+06  1.180527e+06  1.180527e+06  1.180527e+06  1.182106e+06  1.182106e+06  1.182106e+06  1.182106e+06  1.182106e+06  1.182106e+06  1.182106e+06  1.182106e+06  1.182106e+06  1.182106e+06  1.182106e+06  1.195380e+06  1.195380e+06  1.195380e+06  1.195380e+06  1.195380e+06  1.195380e+06  1.195380e+06  1.195380e+06  1.195380e+06  1.195380e+06  1.195380e+06  1.195380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06  1.202380e+06           NaN           NaN           NaN           NaN           NaN           NaN
2008-08   4832.347658   28663.352169   81174.325149  143823.753969  189778.775105  322911.952061  404644.628455  444354.082037  556469.471645  5.778366e+05  5.972233e+05  6.339826e+05  6.655116e+05  7.068361e+05  7.171831e+05  7.421081e+05  7.475395e+05  7.781453e+05  8.136729e+05  8.352770e+05  8.501195e+05  9.010394e+05  9.495607e+05  9.595362e+05  9.958001e+05  9.958001e+05  1.021572e+06  1.021572e+06  1.033163e+06  1.040017e+06  1.040017e+06  1.040017e+06  1.040017e+06  1.044445e+06  1.044445e+06  1.044445e+06  1.044445e+06  1.044445e+06  1.044445e+06  1.056068e+06  1.056068e+06  1.056068e+06  1.056068e+06  1.070068e+06  1.070068e+06  1.087939e+06  1.087939e+06  1.087939e+06  1.087939e+06  1.087939e+06  1.087939e+06  1.087939e+06  1.087939e+06  1.087939e+06  1.087939e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06  1.095352e+06           NaN           NaN           NaN           NaN           NaN           NaN           NaN
2008-09           NaN   43464.271322  129621.055093  182285.166689  272213.301731  360951.618287  416569.049140  443168.263249  512689.862488  5.594782e+05  6.783411e+05  7.202981e+05  7.572994e+05  7.803084e+05  8.243695e+05  8.941447e+05  9.111255e+05  9.622760e+05  9.947346e+05  9.947346e+05  1.006547e+06  1.033435e+06  1.045216e+06  1.060862e+06  1.082445e+06  1.131445e+06  1.145671e+06  1.157629e+06  1.165317e+06  1.179623e+06  1.179623e+06  1.179623e+06  1.179623e+06  1.194177e+06  1.212654e+06  1.212654e+06  1.217840e+06  1.219996e+06  1.224757e+06  1.224757e+06  1.224757e+06  1.234472e+06  1.234472e+06  1.239935e+06  1.239935e+06  1.239935e+06  1.239935e+06  1.239935e+06  1.239935e+06  1.239935e+06  1.239935e+06  1.239935e+06  1.252716e+06  1.256536e+06  1.256536e+06  1.259106e+06  1.259106e+06  1.259106e+06  1.259106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.273106e+06  1.280106e+06  1.280106e+06  1.280106e+06  1.280106e+06  1.280106e+06  1.280106e+06  1.280106e+06           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN
2008-10           NaN   12487.697845   34426.791815   87814.693479  140229.326978  232315.157186  278095.749566  350337.902162  433697.325778  4.812914e+05  5.301353e+05  5.392550e+05  5.778721e+05  6.435479e+05  7.366678e+05  7.499255e+05  8.160420e+05  8.695962e+05  9.143625e+05  9.488226e+05  9.558226e+05  9.826618e+05  1.006112e+06  1.010040e+06  1.010040e+06  1.034500e+06  1.058038e+06  1.058038e+06  1.069794e+06  1.072897e+06  1.097437e+06  1.124372e+06  1.146692e+06  1.153692e+06  1.171005e+06  1.181419e+06  1.181419e+06  1.187304e+06  1.187304e+06  1.187304e+06  1.187304e+06  1.192387e+06  1.192387e+06  1.192387e+06  1.192387e+06  1.192387e+06  1.192387e+06  1.192387e+06  1.192387e+06  1.199763e+06  1.199763e+06  1.199763e+06  1.204699e+06  1.204699e+06  1.204699e+06  1.204699e+06  1.204699e+06  1.204699e+06  1.204699e+06  1.214647e+06  1.214647e+06  1.214647e+06  1.214647e+06  1.214647e+06  1.214647e+06  1.214647e+06  1.214647e+06  1.214647e+06  1.214647e+06  1.214647e+06  1.214647e+06  1.214647e+06  1.214647e+06  1.214647e+06  1.233647e+06  1.233647e+06  1.233647e+06  1.233647e+06  1.233647e+06  1.233647e+06  1.233647e+06  1.233647e+06  1.238830e+06  1.238830e+06  1.238830e+06  1.238830e+06  1.238830e+06  1.238830e+06  1.238830e+06  1.238830e+06  1.249236e+06  1.249236e+06  1.249236e+06  1.249236e+06  1.249236e+06  1.249236e+06  1.249236e+06  1.249236e+06  1.249236e+06  1.249236e+06  1.249236e+06  1.249236e+06  1.249236e+06  1.249236e+06  1.249236e+06  1.249236e+06  1.249236e+06  1.249236e+06  1.249236e+06  1.249236e+06  1.249236e+06           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN

In [ ]:
# NOTE When we run the link_ratio() function, it just gives us the link ratio
# even if it is an incremental triangle (which is not what we usually expect).
# it is by design this way, so just keep in mind.

# prism.link_ratio['Paid'][prism['Line']=='Auto']
prism_cum.link_ratio['Paid'][prism['Line']=='Auto']

               1-2        2-3       3-4       4-5       5-6       6-7       7-8       8-9      9-10     10-11     11-12     12-13     13-14     14-15     15-16     16-17     17-18     18-19     19-20     20-21     21-22     22-23     23-24     24-25     25-26     26-27     27-28     28-29     29-30     30-31     31-32     32-33     33-34     34-35     35-36     36-37     37-38     38-39     39-40     40-41     41-42     42-43     43-44     44-45     45-46     46-47     47-48     48-49     49-50     50-51     51-52     52-53     53-54     54-55     55-56     56-57     57-58     58-59     59-60     60-61     61-62     62-63     63-64     64-65     65-66     66-67     67-68     68-69  69-70     70-71     71-72     72-73     73-74     74-75     75-76     76-77  77-78     78-79   79-80  80-81     81-82     82-83     83-84  84-85    85-86     86-87  87-88  88-89     89-90   90-91  91-92  92-93     93-94  94-95  95-96  96-97     97-98  98-99  99-100  100-101  101-102  102-103  103-104  104-105   105-106  106-107  107-108  108-109  109-110  110-111  111-112  112-113  113-114  114-115  115-116  116-117  117-118  118-119  119-120
2008-01        NaN        NaN  1.424145  1.856350  1.723885  1.085597  1.409515  1.031581  1.271916  1.117415  1.054004  1.040276  1.102623  1.073882  1.117038  1.065043  1.056469  1.024274  1.025796  1.009043  1.080282  1.037832  1.023042  1.033404  1.044922  1.000000  1.013621  1.007638  1.020204  1.006548  1.000000  1.003705  1.033143  1.011005  1.000000  1.000000  1.005035  1.006163  1.000000  1.007642  1.000000  1.006361  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.005961  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.004854  1.000000  1.000000  1.006410  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000    1.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000    1.0  1.000000  1.0000    1.0  1.000000  1.000000  1.000000    1.0  1.00000  1.000000    1.0    1.0  1.000000  1.0000    1.0    1.0  1.000000    1.0    1.0    1.0  1.000000    1.0     1.0      1.0      1.0      1.0      1.0      1.0  1.000000      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0
2008-02        NaN   1.769032  2.553970  1.488522  1.310289  1.255321  1.215399  1.087173  1.170555  1.022050  1.153147  1.077828  1.050029  1.048207  1.065063  1.007424  1.038702  1.026883  1.030208  1.044417  1.047932  1.004534  1.026603  1.017665  1.036965  1.016348  1.011509  1.013665  1.003845  1.010082  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.013719  1.000000  1.000000  1.000000  1.006766  1.000000  1.012934  1.008808  1.000000  1.002534  1.000000  1.000000  1.000000  1.004318  1.017731  1.000000  1.026954  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.005080  1.000000    1.0  1.006044  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000    1.0  1.000000  1.0000    1.0  1.000000  1.000000  1.000000    1.0  1.00000  1.000000    1.0    1.0  1.000000  1.0000    1.0    1.0  1.000000    1.0    1.0    1.0  1.000000    1.0     1.0      1.0      1.0      1.0      1.0      1.0  1.000000      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      NaN
2008-03        NaN   1.572667  2.177934  1.326359  1.376627  1.041252  1.226651  1.180458  1.076536  1.106825  1.093591  1.121399  1.074333  1.076867  1.066179  1.074892  1.067874  1.091682  1.000547  1.028406  1.032299  1.025275  1.033696  1.040290  1.003726  1.028555  1.005322  1.000000  1.004089  1.005016  1.000000  1.013265  1.004813  1.002125  1.000000  1.025369  1.001411  1.000000  1.000000  1.000749  1.006710  1.018186  1.000000  1.008575  1.000000  1.000000  1.000000  1.000000  1.018815  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.004702  1.000000  1.000000  1.000000    1.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000    1.0  1.000000  1.0000    1.0  1.000000  1.000000  1.000000    1.0  1.00000  1.000000    1.0    1.0  1.000000  1.0000    1.0    1.0  1.000000    1.0    1.0    1.0  1.001418    1.0     1.0      1.0      1.0      1.0      1.0      1.0  1.000000      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      NaN      NaN
2008-04        NaN   1.577504  2.460650  1.253219  1.263954  1.352840  1.477235  1.055557  1.095798  1.057414  1.123557  1.029485  1.075285  1.033278  1.043765  1.030212  1.083543  1.031658  1.014433  1.047627  1.038921  1.018831  1.007818  1.018862  1.000000  1.018159  1.000000  1.008335  1.014432  1.010886  1.013560  1.046849  1.000000  1.007972  1.000000  1.002678  1.018191  1.007436  1.000000  1.000000  1.015862  1.000000  1.000000  1.000000  1.014613  1.005465  1.000000  1.007071  1.004577  1.000000  1.000000  1.003108  1.000000  1.000000  1.000000  1.000000  1.000000  1.002952  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000    1.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.006853  1.000000    1.0  1.000000  1.0000    1.0  1.000000  1.000000  1.000000    1.0  1.00000  1.000000    1.0    1.0  1.000000  1.0000    1.0    1.0  1.000000    1.0    1.0    1.0  1.000000    1.0     1.0      1.0      1.0      1.0      1.0      1.0  1.000000      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      NaN      NaN      NaN
2008-05        NaN   3.249017  1.163019  1.399647  1.547672  1.099051  1.064550  1.145206  1.219987  1.129771  1.096112  1.089651  1.068128  1.056359  1.064371  1.110610  1.039733  1.056584  1.014976  1.054832  1.003651  1.008383  1.012350  1.013946  1.005721  1.002441  1.006870  1.000000  1.003938  1.006036  1.016286  1.004676  1.005831  1.000000  1.004168  1.000000  1.017977  1.019757  1.000000  1.004795  1.003367  1.005559  1.000922  1.000000  1.003842  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.003121  1.000000  1.000000  1.001976  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000    1.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.005515  1.000000    1.0  1.000000  1.0000    1.0  1.000000  1.000000  1.000000    1.0  1.00000  1.014778    1.0    1.0  1.000000  1.0000    1.0    1.0  1.000000    1.0    1.0    1.0  1.000000    1.0     1.0      1.0      1.0      1.0      1.0      1.0  1.000000      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      NaN      NaN      NaN      NaN
2008-06        NaN   2.291642  1.751806  1.284307  1.208620  1.117795  1.220373  1.127228  1.115955  1.032946  1.075050  1.077540  1.019639  1.030688  1.021442  1.051434  1.028951  1.103738  1.017400  1.018142  1.008022  1.028986  1.024863  1.009539  1.006761  1.022352  1.004356  1.006540  1.041477  1.015375  1.008946  1.009426  1.001373  1.002127  1.000000  1.000000  1.000000  1.000000  1.004424  1.000000  1.009688  1.000000  1.000000  1.000000  1.013427  1.004518  1.000000  1.000000  1.005823  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.009989  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000    1.0  1.003894  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000    1.0  1.000000  1.0000    1.0  1.000000  1.000000  1.000000    1.0  1.00000  1.000000    1.0    1.0  1.000000  1.0000    1.0    1.0  1.000000    1.0    1.0    1.0  1.000000    1.0     1.0      1.0      1.0      1.0      1.0      1.0  1.000000      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      NaN      NaN      NaN      NaN      NaN
2008-07        NaN   2.643630  1.834728  1.542140  1.343450  1.399259  1.204799  1.086068  1.063258  1.095329  1.058261  1.084959  1.062041  1.055449  1.018520  1.024963  1.028263  1.010796  1.036600  1.024211  1.007582  1.031683  1.022397  1.014879  1.027134  1.006661  1.006293  1.000000  1.031368  1.000000  1.021302  1.019064  1.010083  1.001107  1.003729  1.008874  1.006410  1.003186  1.000000  1.000000  1.009746  1.000000  1.000000  1.026588  1.009305  1.001955  1.008754  1.000000  1.000884  1.000000  1.000000  1.006488  1.000000  1.005098  1.000000  1.000000  1.000000  1.000000  1.000000  1.001338  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000    1.0  1.000000  1.011230  1.000000  1.000000  1.000000  1.000000  1.000000    1.0  1.000000  1.0000    1.0  1.000000  1.000000  1.005856    1.0  1.00000  1.000000    1.0    1.0  1.000000  1.0000    1.0    1.0  1.000000    1.0    1.0    1.0  1.000000    1.0     1.0      1.0      1.0      1.0      1.0      1.0  1.000000      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0      NaN      NaN      NaN      NaN      NaN      NaN
2008-08   5.931558   2.831990  1.771789  1.319523  1.701518  1.253111  1.098134  1.252311  1.038398  1.033550  1.061550  1.049732  1.062094  1.014638  1.034754  1.007319  1.040942  1.045657  1.026551  1.017770  1.059897  1.053850  1.010505  1.037793  1.000000  1.025881  1.000000  1.011346  1.006634  1.000000  1.000000  1.000000  1.004258  1.000000  1.000000  1.000000  1.000000  1.000000  1.011128  1.000000  1.000000  1.000000  1.013257  1.000000  1.016700  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.006814  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000    1.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000    1.0  1.000000  1.0000    1.0  1.000000  1.000000  1.000000    1.0  1.00000  1.000000    1.0    1.0  1.000000  1.0000    1.0    1.0  1.000000    1.0    1.0    1.0  1.000000    1.0     1.0      1.0      1.0      1.0      1.0      1.0  1.000000      1.0      1.0      1.0      1.0      1.0      1.0      1.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2008-09        NaN   2.982244  1.406293  1.493338  1.325988  1.154086  1.063853  1.156874  1.091261  1.212453  1.061852  1.051370  1.030383  1.056466  1.084641  1.018991  1.056140  1.033731  1.000000  1.011874  1.026714  1.011400  1.014969  1.020345  1.045268  1.012573  1.010438  1.006641  1.012277  1.000000  1.000000  1.000000  1.012338  1.015472  1.000000  1.004277  1.001771  1.003902  1.000000  1.000000  1.007932  1.000000  1.004426  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.010308  1.003049  1.000000  1.002045  1.000000  1.000000  1.000000  1.011119  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000    1.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000    1.0  1.000000  1.0000    1.0  1.000000  1.000000  1.000000    1.0  1.00000  1.000000    1.0    1.0  1.000000  1.0000    1.0    1.0  1.000000    1.0    1.0    1.0  1.000000    1.0     1.0      1.0      1.0      1.0      1.0      1.0  1.005498      1.0      1.0      1.0      1.0      1.0      1.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2008-10        NaN   2.756857  2.550766  1.596878  1.656680  1.197062  1.259774  1.237940  1.109740  1.101485  1.017203  1.071612  1.113651  1.144698  1.017997  1.088164  1.065627  1.051479  1.037688  1.007378  1.028080  1.023864  1.003904  1.000000  1.024217  1.022754  1.000000  1.011111  1.002900  1.022873  1.024543  1.019851  1.006105  1.015007  1.008893  1.000000  1.004982  1.000000  1.000000  1.000000  1.004281  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.006185  1.000000  1.000000  1.004115  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.008258  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000    1.0  1.000000  1.000000  1.000000  1.000000  1.015642  1.000000  1.000000    1.0  1.000000  1.0000    1.0  1.000000  1.004201  1.000000    1.0  1.00000  1.000000    1.0    1.0  1.000000  1.0084    1.0    1.0  1.000000    1.0    1.0    1.0  1.000000    1.0     1.0      1.0      1.0      1.0      1.0      1.0  1.000000      1.0      1.0      1.0      1.0      1.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2008-11        NaN   1.207061  2.438684  1.633716  1.180851  1.158814  1.247291  1.089103  1.088074  1.042522  1.065347  1.081463  1.110916  1.137754  1.033085  1.052057  1.063597  1.065659  1.027318  1.019450  1.016475  1.015140  1.061900  1.057843  1.021822  1.007965  1.012659  1.013367  1.013793  1.002422  1.000000  1.004499  1.004139  1.016833  1.009590  1.018139  1.005917  1.012240  1.000000  1.006980  1.000000  1.000000  1.000000  1.000000  1.000000  1.006004  1.000000  1.003165  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.005042  1.013642  1.000000  1.000000  1.000000  1.000922  1.000000  1.000000  1.000000    1.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000    1.0  1.003961  1.0000    1.0  1.000000  1.000000  1.000000    1.0  1.00000  1.000000    1.0    1.0  1.000000  1.0000    1.0    1.0  1.000000    1.0    1.0    1.0  1.000000    1.0     1.0      1.0      1.0      1.0      1.0      1.0  1.000000      1.0      1.0      1.0      1.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2008-12   3.721445   5.045407  2.273959  1.454887  1.242282  1.111845  1.141088  1.166836  1.076106  1.100538  1.100004  1.093328  1.055724  1.062085  1.021177  1.062597  1.072920  1.031828  1.037740  1.046308  1.026117  1.035840  1.006825  1.035255  1.015309  1.013789  1.027092  1.006901  1.006853  1.020942  1.007957  1.013783  1.000000  1.009098  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.014768  1.000000  1.000000  1.000000  1.000000  1.003327  1.010948  1.000000  1.005727  1.000000  1.000000  1.005194  1.000000  1.000000  1.000000  1.008310  1.016727  1.000000  1.000000  1.000000  1.000000  1.007231  1.000000  1.013499  1.000000  1.000000  1.000000  1.000000    1.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000    1.0  1.000000  1.0000    1.0  1.000000  1.000000  1.000000    1.0  1.00000  1.000000    1.0    1.0  1.000000  1.0000    1.0    1.0  1.000000    1.0    1.0    1.0  1.000000    1.0     1.0      1.0      1.0      1.0      1.0      1.0  1.000000      1.0      1.0      1.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2009-01        NaN   4.234319  1.862496  1.321215  1.558902  1.238305  1.147283  1.229101  1.120599  1.125504  1.130372  1.112861  1.086391  1.091645  1.063664  1.000000  1.038439  1.046281  1.014050  1.035760  1.013631  1.039309  1.044016  1.005209  1.035586  1.025455  1.020612  1.004926  1.009332  1.008506  1.011608  1.000000  1.020112  1.018546  1.000000  1.005982  1.000000  1.005946  1.016094  1.005817  1.011568  1.000000  1.001959  1.009555  1.000000  1.000000  1.005167  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.006271  1.002764  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.005130  1.000000    1.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000    1.0  1.000000  1.0000    1.0  1.000000  1.000000  1.000000    1.0  1.00000  1.000000    1.0    1.0  1.000000  1.0000    1.0    1.0  1.000000    1.0    1.0    1.0  1.000000    1.0     1.0      1.0      1.0      1.0      1.0      1.0  1.000000      1.0      1.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2009-02   4.398833   1.822594  1.711357  1.477947  1.275583  1.431732  1.149724  1.148853  1.109142  1.083752  1.139533  1.060129  1.146585  1.032511  1.082944  1.074803  1.012281  1.019591  1.029604  1.044341  1.018322  1.003755  1.021769  1.015960  1.016343  1.032172  1.022185  1.005496  1.026098  1.008906  1.017257  1.000000  1.000000  1.000000  1.000000  1.004255  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.007022  1.000000  1.011325  1.000000  1.006831  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000    1.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000    1.0  1.000000  1.0000    1.0  1.000000  1.000000  1.000000    1.0  1.00504  1.000000    1.0    1.0  1.000000  1.0000    1.0    1.0  1.000000    1.0    1.0    1.0  1.000000    1.0     1.0      1.0      1.0      1.0      1.0      1.0  1.000000      1.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2009-03        NaN   1.837509  1.836603  1.395449  1.218573  1.308415  1.227429  1.126654  1.175860  1.063239  1.059317  1.097653  1.026871  1.069023  1.040409  1.014772  1.014075  1.029252  1.037676  1.060588  1.032159  1.010925  1.017676  1.000000  1.027117  1.014769  1.000000  1.000000  1.024987  1.022232  1.019748  1.030493  1.003553  1.001319  1.005882  1.033556  1.000000  1.002632  1.000000  1.000000  1.007941  1.003223  1.001390  1.001815  1.000000  1.000000  1.000000  1.000000  1.002466  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.007946  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000    1.0  1.000000  1.000000  1.000000  1.001303  1.000000  1.000000  1.000000    1.0  1.000000  1.0000    1.0  1.000000  1.000000  1.000000    1.0  1.00000  1.000000    1.0    1.0  1.000000  1.0000    1.0    1.0  1.000000    1.0    1.0    1.0  1.000000    1.0     1.0      1.0      1.0      1.0      1.0      1.0  1.000000      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2009-04        NaN   2.160561  1.723767  1.180829  1.347857  1.222718  1.213335  1.170362  1.167081  1.059538  1.115082  1.146524  1.134472  1.101926  1.041089  1.060179  1.016805  1.044613  1.043261  1.048253  1.036011  1.000000  1.004254  1.013824  1.031227  1.003261  1.005227  1.008560  1.008245  1.000000  1.000000  1.008209  1.012815  1.000000  1.000000  1.000000  1.000000  1.000000  1.011549  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.003415  1.006684  1.000000  1.000000  1.000000  1.000000  1.000000  1.004938  1.001280  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000    1.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000    1.0  1.000000  1.0000    1.0  1.000000  1.000000  1.000000    1.0  1.00000  1.000000    1.0    1.0  1.000000  1.0000    1.0    1.0  1.000000    1.0    1.0    1.0  1.000000    1.0     1.0      1.0      1.0      1.0      1.0      1.0       NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

In [82]:
prism_incr = prism_cum.cum_to_incr()

In [84]:
prism_incr.link_ratio['Paid'][prism['Line']=='Auto']

               1-2        2-3       3-4       4-5       5-6       6-7       7-8       8-9      9-10      10-11     11-12     12-13     13-14     14-15     15-16     16-17     17-18     18-19      19-20      20-21     21-22      22-23     23-24      24-25      25-26     26-27      27-28      28-29      29-30     30-31      31-32     32-33     33-34     34-35     35-36     36-37     37-38     38-39     39-40     40-41     41-42      42-43     43-44     44-45     45-46     46-47     47-48     48-49     49-50     50-51     51-52     52-53     53-54     54-55     55-56     56-57     57-58     58-59     59-60  60-61     61-62     62-63  63-64  64-65  65-66  66-67     67-68     68-69  69-70  70-71  71-72  72-73  73-74  74-75  75-76  76-77  77-78  78-79  79-80  80-81  81-82  82-83  83-84  84-85  85-86  86-87  87-88  88-89  89-90  90-91  91-92  92-93  93-94  94-95  95-96  96-97  97-98  98-99  99-100  100-101  101-102  102-103  103-104  104-105  105-106  106-107  107-108  108-109  109-110  110-111  111-112  112-113  113-114  114-115  115-116  116-117  117-118  118-119  119-120
2008-01        NaN        NaN  0.424145  2.875351  1.569199  0.203845  5.193713  0.108699  8.882017   0.549221  0.513943  0.786084  2.650578  0.793824  1.701158  0.620788  0.924640  0.454136   1.088518   0.359616  8.957655   0.509064  0.632098   1.483141   1.389712       NaN        NaN   0.568409   2.665312  0.330648        NaN       NaN  8.979324  0.343064       NaN       NaN       NaN  1.230244       NaN       NaN       NaN        NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2008-02        NaN   0.769032  3.574653  0.802892  0.945448  1.078169  1.059042  0.491879  2.127056   0.151331  7.098727  0.586016  0.692848  1.011787  1.414723  0.121522  5.252104  0.721489   1.153915   1.514769  1.127065   0.099122  5.894263   0.681697   2.129535  0.458612   0.715472   1.200994   0.285234  2.632078        NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN       NaN       NaN       NaN       NaN  0.689814       NaN       NaN       NaN       NaN       NaN       NaN  4.123656       NaN       NaN       NaN       NaN       NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2008-03        NaN   0.572667  3.234860  0.603419  1.530653  0.150783  5.720931  0.976649  0.500660   1.502565  0.969710  1.418519  0.686632  1.110959  0.927138  1.206548  0.974163  1.442447   0.006507  52.006027  1.169352   0.807797  1.366876   1.235988   0.096193  7.693281   0.191705        NaN        NaN  1.231558        NaN       NaN  0.367639  0.443572       NaN       NaN  0.057019       NaN       NaN       NaN  8.961453   2.728407       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2008-04        NaN   0.577504  3.989895  0.426580  1.306349  1.689585  1.829788  0.171972  1.820110   0.656732  2.275619  0.268123  2.628572  0.475311  1.358885  0.720526  2.848823  0.410592   0.470338   3.347547  0.856134   0.502646  0.422989   2.431488        NaN       NaN        NaN        NaN   1.745870  0.765204   1.259174  3.501810       NaN       NaN       NaN       NaN  6.811156  0.416203       NaN       NaN       NaN        NaN       NaN       NaN       NaN  0.379463       NaN       NaN  0.651828       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2008-05        NaN   2.249017  0.235504  2.851176  1.918062  0.279908  0.716236  2.394722  1.734987   0.719672  0.836743  1.022421  0.828055  0.883617  1.206530  1.828918  0.398956  1.480674   0.279637   3.716253  0.070230   2.304595  1.485624   1.143138   0.415988  0.429143   2.820805        NaN        NaN  1.538896   2.714286  0.291816  1.252626       NaN       NaN       NaN       NaN  1.118779       NaN       NaN  0.705451   1.656851  0.166762       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2008-06        NaN   1.291642  1.333861  0.662472  0.942406  0.682434  2.091190  0.704559  1.027346   0.317077  2.352987  1.110720  0.272919  1.593251  0.720152  2.450209  0.591838  3.686914   0.185132   1.060750  0.450197   3.642456  0.882602   0.393211   0.715492  3.328483   0.199254   1.507809   6.383486  0.386072   0.590769  1.063072  0.147037  1.551466       NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN       NaN       NaN       NaN  0.341012       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2008-07        NaN   1.643630  1.342585  1.191621  0.976958  1.561754  0.717746  0.506322  0.798239   1.602316  0.669415  1.543206  0.792286  0.949212  0.352520  1.372859  1.160433  0.392781   3.426772   0.685710  0.320768   4.210141  0.729318   0.679211   1.850746  0.252139   0.951024        NaN        NaN       NaN        NaN  0.914033  0.538984  0.110870  3.373210  2.388538  0.728701  0.500308       NaN       NaN       NaN        NaN       NaN       NaN  0.359284  0.212019  4.487434       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2008-08   4.931558   2.203473  1.193073  0.733527  2.897032  0.613917  0.485846  2.823393  0.190582   0.907313  1.896116  0.857713  1.310683  0.250383  2.408925  0.217907  5.635034  1.160815   0.608092   0.687023  3.430674   0.952898  0.205590   3.635297        NaN       NaN        NaN        NaN   0.591287       NaN        NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2008-09        NaN   1.982244  0.611259  1.707579  0.986769  0.626758  0.478253  2.613671  0.673005   2.540437  0.352986  0.881889  0.621840  1.914956  1.583604  0.243363  3.012269  0.634569        NaN        NaN  2.276380   0.438132  1.328113   1.379495   2.270221  0.290326   0.840590   0.642853   1.860989       NaN        NaN       NaN       NaN  1.269517       NaN       NaN  0.415784  2.207982       NaN       NaN       NaN        NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN  0.298831       NaN       NaN       NaN       NaN       NaN       NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2008-10        NaN   1.756857  2.433460  0.981770  1.756873  0.497151  1.578008  1.153889  0.570951   1.026257  0.186712  4.234476  1.700688  1.417874  0.142372  4.987052  0.809998  0.835906   0.769778   0.203134  3.834170   0.873723  0.167505        NaN        NaN  0.962326        NaN        NaN   0.263936  7.908936   1.097568  0.828681  0.313619  2.473377  0.601448       NaN       NaN       NaN       NaN       NaN       NaN        NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2008-11        NaN   0.207061  8.386813  1.074199  0.466234  1.036963  1.804398  0.449419  1.076533   0.525312  1.602156  1.328079  1.472468  1.379720  0.273263  1.625460  1.285274  1.098092   0.443383   0.731411  0.863507   0.934118  4.150453   0.992309   0.399088  0.372963   1.601967   1.069318   1.045637  0.178050        NaN       NaN  0.924123  4.083726  0.579307  1.909578  0.332100  2.080912       NaN       NaN       NaN        NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN    NaN  2.719382       NaN    NaN    NaN    NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2008-12   2.721445   5.531900  1.588874  0.811953  0.774902  0.573479  1.402538  1.349332  0.532280   1.421558  1.094695  1.026574  0.652798  1.176250  0.362278  3.018454  1.237832  0.468297   1.223495   1.273352  0.590106   1.408104  0.197257   5.200729   0.449556  0.914473   1.991864   0.261614   1.000000  3.076700   0.387899  1.745969       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN       NaN       NaN       NaN       NaN  3.301236       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN  2.029622       NaN       NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2009-01        NaN   3.234319  1.129166  0.693641  2.298860  0.664685  0.765325  1.784622  0.647002   1.166174  1.169162  0.978546  0.851853  1.152460  0.758345       NaN       NaN  1.250288   0.317640   2.580917  0.394819   2.922997  1.163759   0.123549   6.867459  0.740773   0.830342   0.243910   1.903707  0.920015   1.376303       NaN       NaN  0.940679       NaN       NaN       NaN       NaN  2.722736  0.367278  2.000000        NaN       NaN  4.886071       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN  0.443525       NaN       NaN       NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2009-02   3.398833   1.064617  1.576130  1.149828  0.852180  1.998347  0.496524  1.143035  0.842363   0.851114  1.805569  0.491054  2.584454  0.254302  2.634174  0.976662  0.176464  1.614798   1.540681   1.542148  0.431531   0.208686  5.819335   0.749138   1.040333  2.000672   0.711761   0.253229   4.774671  0.350167   1.954960       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2009-03        NaN   0.837509  1.835520  0.868134  0.771293  1.719454  0.964840  0.683549  1.564372   0.422835  0.997297  1.743952  0.302042  2.637673  0.625850  0.380327  0.966914  2.107569   1.325638   1.668729  0.562943   0.350641  1.635585        NaN        NaN  0.559397        NaN        NaN        NaN  0.911983   0.908036  1.574542  0.120061  0.372695  4.464229  5.738287       NaN       NaN       NaN       NaN       NaN   0.409095  0.432633  1.307971       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2009-04        NaN   1.160561  1.347402  0.430673  2.271537  0.862976  1.171207  0.968930  1.147820   0.415883  2.047992  1.419729  1.052223  0.859895  0.444218  1.524786  0.296048  2.699429   1.012944   1.163660  0.782291        NaN       NaN   3.263384   2.290118  0.107695   1.608058   1.646219   0.971407       NaN        NaN       NaN  1.573906       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN       NaN       NaN       NaN       NaN       NaN  1.964204       NaN       NaN       NaN       NaN       NaN       NaN  0.260421       NaN       NaN       NaN       NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2009-05        NaN   4.395554  0.857372  0.928120  1.344905  0.801149  0.929049  1.497096  0.570346   0.325111  3.315725  1.030751  0.968300  0.719337  1.403998  0.269318  1.301675  1.141667   0.529515   1.352260  3.694925   0.477559  0.795157   0.280268   2.469293  1.240422   0.450747   0.105277  10.428015  0.744519   1.528882       NaN       NaN  1.223866  1.593023  0.594577       NaN       NaN  0.451366  0.816235  2.714286        NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN       NaN       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

We could have also done this

In [85]:
prism.incr_to_cum(inplace=True)

            Triangle Summary
Valuation:           2017-12
Grain:                  OMDM
Shape:      (2, 2, 120, 120)
Index:          [Line, Type]
Columns:    [Paid, Incurred]

In [86]:
prism.is_cumulative

True

In [87]:
prism_OYDY = prism.grain('OYDY')

In [91]:
prism_OYDY[prism_OYDY['Line']=="Auto"]['Paid']

               12            24            36            48            60            72            84            96            108           120
2008  3.404254e+06  1.006178e+07  1.295414e+07  1.382220e+07  1.418232e+07  1.435217e+07  1.442832e+07  1.446425e+07  1.447666e+07  1.448366e+07
2009  3.609385e+06  1.081563e+07  1.359175e+07  1.470284e+07  1.505151e+07  1.514915e+07  1.518844e+07  1.519544e+07  1.520079e+07           NaN
2010  4.067321e+06  1.177617e+07  1.512759e+07  1.629239e+07  1.688425e+07  1.702993e+07  1.710237e+07  1.711296e+07           NaN           NaN
2011  4.125232e+06  1.267985e+07  1.619172e+07  1.744130e+07  1.793601e+07  1.816584e+07  1.823906e+07           NaN           NaN           NaN
2012  4.584036e+06  1.340190e+07  1.725788e+07  1.870597e+07  1.917567e+07  1.940706e+07           NaN           NaN           NaN           NaN
2013  4.889623e+06  1.407144e+07  1.797535e+07  1.946453e+07  2.002725e+07           NaN           NaN           NaN           NaN           NaN
2014  5.546158e+06  1.544215e+07  1.986253e+07  2.142708e+07           NaN           NaN           NaN           NaN           NaN           NaN
2015  5.909029e+06  1.705660e+07  2.186747e+07           NaN           NaN           NaN           NaN           NaN           NaN           NaN
2016  6.080962e+06  1.794788e+07           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN
2017  6.396536e+06           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN

Look at triangle with its `development` axis *expressed* as a valuation rather than an age.

In [94]:
prism_OYDY_val = prism_OYDY.dev_to_val()
prism_OYDY_val['Paid'].sum()

              2008          2009          2010          2011          2012          2013          2014          2015          2016          2017
2008  3.404254e+06  1.119109e+07  7.461301e+07  1.503428e+08  1.509829e+08  1.511527e+08  1.512289e+08  1.512648e+08  1.512772e+08  1.512842e+08
2009           NaN  3.609385e+06  1.100293e+07  8.072635e+07  1.569708e+08  1.575995e+08  1.576971e+08  1.577364e+08  1.577434e+08  1.577487e+08
2010           NaN           NaN  4.067321e+06  1.239678e+07  7.421004e+07  1.610496e+08  1.616415e+08  1.617871e+08  1.618596e+08  1.618702e+08
2011           NaN           NaN           NaN  4.125232e+06  1.318314e+07  8.123977e+07  1.614129e+08  1.621876e+08  1.624175e+08  1.624907e+08
2012           NaN           NaN           NaN           NaN  4.584036e+06  1.400118e+07  7.779452e+07  1.521184e+08  1.525881e+08  1.528195e+08
2013           NaN           NaN           NaN           NaN           NaN  4.889623e+06  1.460774e+07  8.441850e+07  1.611103e+08  1.616730e+08
2014           NaN           NaN           NaN           NaN           NaN           NaN  5.546158e+06  1.640813e+07  7.725679e+07  1.549699e+08
2015           NaN           NaN           NaN           NaN           NaN           NaN           NaN  5.909029e+06  1.742761e+07  8.091458e+07
2016           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN  6.080962e+06  1.858806e+07
2017           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN  6.396536e+06

In [97]:
prism_OYDY.loc['Home']['Paid']

      12            24            36            48            60            72            84            96            108           120
2008  NaN  1.129305e+06  6.165887e+07  1.365206e+08  1.368006e+08  1.368006e+08  1.368006e+08  1.368006e+08  1.368006e+08  1.368006e+08
2009  NaN  1.872920e+05  6.713460e+07  1.422679e+08  1.425479e+08  1.425479e+08  1.425479e+08  1.425479e+08  1.425479e+08           NaN
2010  NaN  6.206026e+05  5.908246e+07  1.447572e+08  1.447572e+08  1.447572e+08  1.447572e+08  1.447572e+08           NaN           NaN
2011  NaN  5.032956e+05  6.504805e+07  1.439716e+08  1.442516e+08  1.442516e+08  1.442516e+08           NaN           NaN           NaN
2012  NaN  5.992768e+05  6.053664e+07  1.334124e+08  1.334124e+08  1.334124e+08           NaN           NaN           NaN           NaN
2013  NaN  5.363029e+05  6.644316e+07  1.416458e+08  1.416458e+08           NaN           NaN           NaN           NaN           NaN
2014  NaN  9.659729e+05  5.739426e+07  1.335428e+08           NaN           NaN           NaN           NaN           NaN           NaN
2015  NaN  3.710149e+05  5.904711e+07           NaN           NaN           NaN           NaN           NaN           NaN           NaN
2016  NaN  6.401785e+05           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN
2017  NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN

In [98]:
prism_df_2011 = prism_df.copy()
prism_df_2011.loc[
    (prism_df_2011["AccidentDate"] >= "2011-01-01")
    & (prism_df_2011["AccidentDate"] < "2012-01-01"),
    "Paid",
] = None  # Let's assume we hav no payments for losses occurred in 2011
prism_2011 = cl.Triangle(
    data=prism_df_2011,
    origin="AccidentDate",
    origin_format="%Y-%m-%d",
    development="PaymentDate",
    development_format="%Y-%m-%d",
    columns=["Paid", "Incurred"],
    index=["Line", "Type"],
    cumulative=False,
)
prism_2011.incr_to_cum(inplace=True)
prism_2011_OYDY = prism_2011.grain("OYDY")
prism_2011_OYDY.loc["Home"]["Paid"]

      12            24            36            48            60            72            84            96            108           120
2008  NaN  1.129305e+06  6.165887e+07  1.365206e+08  1.368006e+08  1.368006e+08  1.368006e+08  1.368006e+08  1.368006e+08  1.368006e+08
2009  NaN  1.872920e+05  6.713460e+07  1.422679e+08  1.425479e+08  1.425479e+08  1.425479e+08  1.425479e+08  1.425479e+08           NaN
2010  NaN  6.206026e+05  5.908246e+07  1.447572e+08  1.447572e+08  1.447572e+08  1.447572e+08  1.447572e+08           NaN           NaN
2011  NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN
2012  NaN  5.992768e+05  6.053664e+07  1.334124e+08  1.334124e+08  1.334124e+08           NaN           NaN           NaN           NaN
2013  NaN  5.363029e+05  6.644316e+07  1.416458e+08  1.416458e+08           NaN           NaN           NaN           NaN           NaN
2014  NaN  9.659729e+05  5.739426e+07  1.335428e+08           NaN           NaN           NaN           NaN           NaN           NaN
2015  NaN  3.710149e+05  5.904711e+07           NaN           NaN           NaN           NaN           NaN           NaN           NaN
2016  NaN  6.401785e+05           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN
2017  NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN

In [99]:
prism_2011_OYDY_droppedna = prism_2011_OYDY.loc["Home"].dropna()
prism_2011_OYDY_droppedna.loc["Home"]["Paid"]

               24            36            48            60            72            84            96            108           120
2008  1.129305e+06  6.165887e+07  1.365206e+08  1.368006e+08  1.368006e+08  1.368006e+08  1.368006e+08  1.368006e+08  1.368006e+08
2009  1.872920e+05  6.713460e+07  1.422679e+08  1.425479e+08  1.425479e+08  1.425479e+08  1.425479e+08  1.425479e+08           NaN
2010  6.206026e+05  5.908246e+07  1.447572e+08  1.447572e+08  1.447572e+08  1.447572e+08  1.447572e+08           NaN           NaN
2011           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN
2012  5.992768e+05  6.053664e+07  1.334124e+08  1.334124e+08  1.334124e+08           NaN           NaN           NaN           NaN
2013  5.363029e+05  6.644316e+07  1.416458e+08  1.416458e+08           NaN           NaN           NaN           NaN           NaN
2014  9.659729e+05  5.739426e+07  1.335428e+08           NaN           NaN           NaN           NaN           NaN           NaN
2015  3.710149e+05  5.904711e+07           NaN           NaN           NaN           NaN           NaN           NaN           NaN
2016  6.401785e+05           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN

In [100]:
prism_OYDY.to_pickle('../data/prism_OYDY.pkl')

In [112]:
prism_OYDY_read = cl.read_pickle('../data/prism_OYDY.pkl')
prism_OYDY.sum(axis='index')['Paid']

               12            24            36            48            60            72            84            96            108           120
2008  3.404254e+06  1.119109e+07  7.461301e+07  1.503428e+08  1.509829e+08  1.511527e+08  1.512289e+08  1.512648e+08  1.512772e+08  1.512842e+08
2009  3.609385e+06  1.100293e+07  8.072635e+07  1.569708e+08  1.575995e+08  1.576971e+08  1.577364e+08  1.577434e+08  1.577487e+08           NaN
2010  4.067321e+06  1.239678e+07  7.421004e+07  1.610496e+08  1.616415e+08  1.617871e+08  1.618596e+08  1.618702e+08           NaN           NaN
2011  4.125232e+06  1.318314e+07  8.123977e+07  1.614129e+08  1.621876e+08  1.624175e+08  1.624907e+08           NaN           NaN           NaN
2012  4.584036e+06  1.400118e+07  7.779452e+07  1.521184e+08  1.525881e+08  1.528195e+08           NaN           NaN           NaN           NaN
2013  4.889623e+06  1.460774e+07  8.441850e+07  1.611103e+08  1.616730e+08           NaN           NaN           NaN           NaN           NaN
2014  5.546158e+06  1.640813e+07  7.725679e+07  1.549699e+08           NaN           NaN           NaN           NaN           NaN           NaN
2015  5.909029e+06  1.742761e+07  8.091458e+07           NaN           NaN           NaN           NaN           NaN           NaN           NaN
2016  6.080962e+06  1.858806e+07           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN
2017  6.396536e+06           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN

In [1]:
import chainladder as cl

In [2]:
benk = cl.Benktander()

In [5]:
raa = cl.load_sample('raa')
raa

         12       24       36       48       60       72       84       96       108      120
1981  5012.0   8269.0  10907.0  11805.0  13539.0  16181.0  18009.0  18608.0  18662.0  18834.0
1982   106.0   4285.0   5396.0  10666.0  13782.0  15599.0  15496.0  16169.0  16704.0      NaN
1983  3410.0   8992.0  13873.0  16141.0  18735.0  22214.0  22863.0  23466.0      NaN      NaN
1984  5655.0  11555.0  15766.0  21266.0  23425.0  26083.0  27067.0      NaN      NaN      NaN
1985  1092.0   9565.0  15836.0  22169.0  25955.0  26180.0      NaN      NaN      NaN      NaN
1986  1513.0   6445.0  11702.0  12935.0  15852.0      NaN      NaN      NaN      NaN      NaN
1987   557.0   4020.0  10946.0  12314.0      NaN      NaN      NaN      NaN      NaN      NaN
1988  1351.0   6947.0  13112.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN
1989  3133.0   5395.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
1990  2063.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

In [7]:
benk.fit(raa,sample_weight=raa)

Benktander()