In [4]:
import ganaka as gn
import chainladder as cl

In [3]:
gn.ReservingSession

ganaka.engine.ReservingSession

In [1]:
import pandas as pd

In [8]:
a = pd.DataFrame([[1,2],[3,4],[5,6]])
a

   0  1
0  1  2
1  3  4
2  5  6

In [18]:
renamed = a.rename(columns={0: 'hi',1:'tata'})
exclude = ['tata']
renamed[exclude]

   tata
0     2
1     4
2     6